-- Database backup for development environment
-- Generated at: 2025-09-26T04:22:51.558Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.acquirer_application_templates (version text NOT NULL DEFAULT '1.0'::text, required_fields ARRAY NOT NULL DEFAULT ARRAY[]::text[], conditional_fields jsonb, template_name text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), pdf_mapping_configuration jsonb, id integer NOT NULL DEFAULT nextval('acquirer_application_templates_id_seq'::regclass), acquirer_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), field_configuration jsonb NOT NULL);
CREATE TABLE public.acquirers (code text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL, display_name text NOT NULL, description text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('acquirers_id_seq'::regclass));
CREATE TABLE public.addresses (geo_accuracy real, country text NOT NULL DEFAULT 'US'::text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), latitude real, state text NOT NULL, street1 text NOT NULL, geocoded_at timestamp without time zone, longitude real, timezone text, type text NOT NULL DEFAULT 'primary'::text, street2 text, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), postal_code text NOT NULL, location_id integer NOT NULL);
CREATE TABLE public.agent_merchants (agent_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), assigned_by text, assigned_at timestamp without time zone DEFAULT now(), merchant_id integer NOT NULL);
CREATE TABLE public.agents (last_name text NOT NULL, email text NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), user_id character varying NOT NULL, company_id integer, commission_rate numeric DEFAULT 5.00, first_name text NOT NULL, phone text NOT NULL, territory text, status text NOT NULL DEFAULT 'active'::text);
CREATE TABLE public.api_keys (is_active boolean DEFAULT true, rate_limit integer DEFAULT 1000, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, name text NOT NULL, key_secret text NOT NULL, contact_email text NOT NULL, organization_name text, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), expires_at timestamp without time zone, last_used_at timestamp without time zone, key_id text NOT NULL);
CREATE TABLE public.api_request_logs (created_at timestamp without time zone NOT NULL DEFAULT now(), response_size integer, response_time integer, ip_address text, method text NOT NULL, request_size integer, status_code integer NOT NULL, endpoint text NOT NULL, user_agent text, error_message text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), api_key_id integer);
CREATE TABLE public.audit_logs (ip_address text NOT NULL, encryption_key_id character varying, request_id character varying, new_values jsonb, application_version text, outcome text, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, request_params jsonb, method text, tags jsonb, geolocation jsonb, user_id character varying, session_id text, old_values jsonb, data_classification text, resource_type text, action text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), resource_id text, details jsonb, metadata jsonb, status_code integer, user_email text, endpoint text, device_info jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), compliance_flags jsonb, category text, resource text NOT NULL, error_message text, severity text DEFAULT 'info'::text, user_agent text, notes text, retention_policy text, response_time integer, updated_at timestamp without time zone DEFAULT now(), request_body jsonb, environment text DEFAULT 'production'::text);
CREATE TABLE public.business_ownership (signature_token text, ownership_percentage numeric NOT NULL, signed_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), digital_signature text, signature_type text, owner_name text NOT NULL, owner_email text NOT NULL, prospect_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), requires_signature boolean NOT NULL DEFAULT false, signature_image_path text, form_submission_id integer, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass));
CREATE TABLE public.campaign_assignments (assigned_by character varying, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), application_id integer, campaign_id integer NOT NULL, prospect_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.campaign_equipment (campaign_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, equipment_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_fee_values (value_type text NOT NULL DEFAULT 'percentage'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), value text NOT NULL, fee_group_fee_item_id integer, campaign_id integer NOT NULL, fee_item_id integer);
CREATE TABLE public.campaigns (id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), is_default boolean NOT NULL DEFAULT false, name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), description text, acquirer text NOT NULL, currency text NOT NULL DEFAULT 'USD'::text, acquirer_id integer, pricing_type_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by character varying, is_active boolean NOT NULL DEFAULT true, equipment text);
CREATE TABLE public.companies (phone text, logo_url text, id integer NOT NULL DEFAULT nextval('companies_id_seq'::regclass), settings jsonb DEFAULT '{}'::jsonb, description text, website text, name text NOT NULL, address jsonb, status text NOT NULL DEFAULT 'active'::text, email text, tax_id character varying, industry text, updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, business_type text, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.data_access_logs (access_reason text, record_id text, field_accessed text, retention_period integer, table_name text NOT NULL, user_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), access_type text NOT NULL, lawful_basis text, data_type text NOT NULL, data_volume integer, audit_log_id integer);
CREATE TABLE public.email_activity (recipient_name character varying, status character varying NOT NULL, opened_at timestamp without time zone, template_name character varying NOT NULL, metadata jsonb, subject text NOT NULL, sent_at timestamp without time zone DEFAULT now(), clicked_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), error_message text, recipient_email character varying NOT NULL, trigger_source character varying, triggered_by character varying, template_id integer);
CREATE TABLE public.email_templates (description text, subject text NOT NULL, is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), category character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), html_content text NOT NULL, text_content text, variables jsonb, name character varying NOT NULL);
CREATE TABLE public.email_triggers (name character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), conditions jsonb, description text, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), template_id integer, trigger_event character varying NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE public.equipment_items (image_url text, model text, updated_at timestamp without time zone NOT NULL DEFAULT now(), description text, status text DEFAULT 'available'::text, is_active boolean NOT NULL DEFAULT true, specifications jsonb DEFAULT '{}'::jsonb, manufacturer text, name text NOT NULL, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), category text, model_number text, price numeric, created_at timestamp without time zone NOT NULL DEFAULT now(), image_data text);
CREATE TABLE public.fee_group_fee_items (id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, fee_group_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, fee_item_group_id integer, is_required boolean NOT NULL DEFAULT false);
CREATE TABLE public.fee_groups (fees jsonb DEFAULT '{}'::jsonb, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text, description text, created_at timestamp without time zone NOT NULL DEFAULT now(), created_by text, is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, category text, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_item_groups (display_order integer NOT NULL DEFAULT 0, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), is_active boolean NOT NULL DEFAULT true, description text);
CREATE TABLE public.fee_items (id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), default_value text, additional_info text, is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, author text NOT NULL DEFAULT 'System'::text, name text NOT NULL, value_type text NOT NULL, description text, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_group_id integer);
CREATE TABLE public.locations (zip_code text NOT NULL, latitude numeric, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), type text NOT NULL DEFAULT 'store'::text, merchant_id integer NOT NULL, name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, longitude numeric, email text, operating_hours jsonb, mid character varying, state text NOT NULL, address text NOT NULL, status text NOT NULL DEFAULT 'active'::text, phone text);
CREATE TABLE public.login_attempts (ip_address character varying NOT NULL, user_agent text, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), username character varying, failure_reason character varying, email character varying, created_at timestamp without time zone DEFAULT now(), success boolean NOT NULL);
CREATE TABLE public.merchant_prospects (created_at timestamp without time zone NOT NULL DEFAULT now(), agent_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), form_data text, notes text, last_name text NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), validation_token text, validated_at timestamp without time zone, email text NOT NULL, current_step integer DEFAULT 0, first_name text NOT NULL, application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text);
CREATE TABLE public.merchants (industry text, legal_name text, business_type text NOT NULL, phone text NOT NULL, business_name text NOT NULL, email text NOT NULL, website text, status text NOT NULL DEFAULT 'active'::text, agent_id integer, processing_fee numeric NOT NULL DEFAULT 2.50, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, dba_name text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), company_id integer, user_id character varying, ein text);
CREATE TABLE public.pdf_form_fields (validation text, position integer NOT NULL, field_name text NOT NULL, section text, form_id integer NOT NULL, is_required boolean DEFAULT false, options ARRAY, field_type text NOT NULL, field_label text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), default_value text);
CREATE TABLE public.pdf_form_submissions (id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), status text DEFAULT 'draft'::text, submission_token text NOT NULL, form_id integer NOT NULL, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), applicant_email text, is_public boolean DEFAULT false, submitted_by text, data text NOT NULL);
CREATE TABLE public.pdf_forms (show_in_navigation boolean DEFAULT false, updated_at timestamp without time zone DEFAULT now(), name text NOT NULL, created_at timestamp without time zone DEFAULT now(), file_size integer NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), navigation_title text, status text DEFAULT 'active'::text, file_name text NOT NULL, uploaded_by text NOT NULL, description text);
CREATE TABLE public.pricing_type_fee_items (created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), is_required boolean NOT NULL DEFAULT true, fee_item_id integer NOT NULL, pricing_type_id integer NOT NULL);
CREATE TABLE public.pricing_types (created_at timestamp without time zone NOT NULL DEFAULT now(), description text, is_active boolean NOT NULL DEFAULT true, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass));
CREATE TABLE public.prospect_applications (rejected_at timestamp without time zone, acquirer_id integer NOT NULL, rejection_reason text, generated_pdf_path text, created_at timestamp without time zone NOT NULL DEFAULT now(), template_id integer NOT NULL, application_data jsonb NOT NULL DEFAULT '{}'::jsonb, approved_at timestamp without time zone, status text NOT NULL DEFAULT 'draft'::text, prospect_id integer NOT NULL, submitted_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('prospect_applications_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), template_version text NOT NULL);
CREATE TABLE public.prospect_owners (signature_token text, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email_sent boolean DEFAULT false, name text NOT NULL, email text NOT NULL, prospect_id integer NOT NULL, updated_at timestamp without time zone DEFAULT now(), created_at timestamp without time zone DEFAULT now(), ownership_percentage numeric NOT NULL, email_sent_at timestamp without time zone);
CREATE TABLE public.prospect_signatures (submitted_at timestamp without time zone DEFAULT now(), prospect_id integer NOT NULL, owner_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature text NOT NULL, signature_type text NOT NULL, signature_token text NOT NULL);
CREATE TABLE public.schema_migrations (id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), environment character varying NOT NULL, checksum character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, migration_id character varying NOT NULL, name character varying NOT NULL);
CREATE TABLE public.security_events (resolution text, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), event_type text NOT NULL, detection_method text, updated_at timestamp without time zone NOT NULL DEFAULT now(), assigned_to character varying, detected_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb, detected_by text, created_at timestamp without time zone NOT NULL DEFAULT now(), investigation_notes text, affected_users jsonb, alert_status text DEFAULT 'new'::text, resolved_at timestamp without time zone, mitigation_actions jsonb, resolved_by character varying, audit_log_id integer, severity text NOT NULL);
CREATE TABLE public.sessions (sid character varying NOT NULL, expire timestamp without time zone NOT NULL, sess jsonb NOT NULL);
CREATE TABLE public.transactions (commission_amount numeric DEFAULT 0, reference_number text, merchant_id integer NOT NULL, status text NOT NULL, created_at timestamp without time zone DEFAULT now(), transaction_id text NOT NULL, net_amount numeric, mid character varying, transaction_type text NOT NULL DEFAULT 'payment'::text, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), commission_rate numeric DEFAULT 0.025, processed_at timestamp with time zone, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, payment_method text NOT NULL, amount numeric NOT NULL, location_id integer, processing_fee numeric);
CREATE TABLE public.two_factor_codes (id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), type character varying NOT NULL, used boolean DEFAULT false, code character varying NOT NULL, expires_at timestamp without time zone NOT NULL, created_at timestamp without time zone DEFAULT now(), user_id character varying NOT NULL);
CREATE TABLE public.user_company_associations (permissions jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), title text, user_id character varying NOT NULL, department text, is_active boolean NOT NULL DEFAULT true, is_primary boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now(), company_id integer NOT NULL, start_date timestamp without time zone, company_role text NOT NULL, end_date timestamp without time zone, id integer NOT NULL DEFAULT nextval('user_company_associations_id_seq'::regclass));
CREATE TABLE public.user_dashboard_preferences (updated_at timestamp without time zone NOT NULL DEFAULT now(), user_id text NOT NULL, position integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), size text NOT NULL DEFAULT 'medium'::text, configuration jsonb DEFAULT '{}'::jsonb, is_visible boolean NOT NULL DEFAULT true, id integer NOT NULL, widget_id text NOT NULL);
CREATE TABLE public.users (phone text NOT NULL DEFAULT ''::character varying, roles ARRAY NOT NULL, id character varying NOT NULL, two_factor_enabled boolean DEFAULT false, last_login_at timestamp without time zone, username character varying NOT NULL, email character varying NOT NULL, password_reset_token character varying, profile_image_url character varying, created_at timestamp without time zone DEFAULT now(), status text NOT NULL DEFAULT 'active'::text, communication_preference text NOT NULL DEFAULT 'email'::text, password_hash character varying NOT NULL, email_verified boolean DEFAULT false, email_verification_token character varying, timezone character varying DEFAULT 'UTC'::character varying, updated_at timestamp without time zone DEFAULT now(), permissions jsonb DEFAULT '{}'::jsonb, last_name character varying, last_login_ip character varying, first_name character varying, two_factor_secret character varying, password_reset_expires timestamp without time zone);