-- Database backup for development environment
-- Generated at: 2025-09-24T17:42:25.016Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (street2 text, latitude real, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), state text NOT NULL, street1 text NOT NULL, geo_accuracy real, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), postal_code text NOT NULL, location_id integer NOT NULL, country text NOT NULL DEFAULT 'US'::text, type text NOT NULL DEFAULT 'primary'::text, geocoded_at timestamp without time zone, timezone text, longitude real);
CREATE TABLE public.agent_merchants (agent_id integer NOT NULL, merchant_id integer NOT NULL, assigned_at timestamp without time zone DEFAULT now(), assigned_by text, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass));
CREATE TABLE public.agents (territory text, last_name text NOT NULL, phone text NOT NULL, email text NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), commission_rate numeric DEFAULT 5.00, user_id character varying NOT NULL, status text NOT NULL DEFAULT 'active'::text, created_at timestamp without time zone DEFAULT now(), first_name text NOT NULL);
CREATE TABLE public.api_keys (id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean DEFAULT true, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, key_secret text NOT NULL, rate_limit integer DEFAULT 1000, contact_email text NOT NULL, organization_name text, key_id text NOT NULL, expires_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, last_used_at timestamp without time zone);
CREATE TABLE public.api_request_logs (api_key_id integer, request_size integer, user_agent text, ip_address text, endpoint text NOT NULL, error_message text, created_at timestamp without time zone NOT NULL DEFAULT now(), response_time integer, method text NOT NULL, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), response_size integer, status_code integer NOT NULL);
CREATE TABLE public.audit_logs (resource text NOT NULL, severity text DEFAULT 'info'::text, user_agent text, encryption_key_id character varying, request_id character varying, new_values jsonb, outcome text, risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, application_version text, request_params jsonb, method text, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), user_id character varying, tags jsonb, geolocation jsonb, data_classification text, resource_type text, session_id text, created_at timestamp without time zone NOT NULL DEFAULT now(), details jsonb, old_values jsonb, action text NOT NULL, device_info jsonb, compliance_flags jsonb, error_message text, resource_id text, notes text, metadata jsonb, retention_policy text, status_code integer, user_email text, response_time integer, endpoint text, updated_at timestamp without time zone DEFAULT now(), request_body jsonb, ip_address text NOT NULL, timestamp timestamp without time zone NOT NULL DEFAULT now(), environment text DEFAULT 'production'::text, category text);
CREATE TABLE public.business_ownership (owner_email text NOT NULL, form_submission_id integer, prospect_id integer, requires_signature boolean NOT NULL DEFAULT false, updated_at timestamp without time zone NOT NULL DEFAULT now(), ownership_percentage numeric NOT NULL, signature_type text, signature_token text, signed_at timestamp without time zone, signature_image_path text, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), owner_name text NOT NULL, digital_signature text);
CREATE TABLE public.campaign_assignments (id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), application_id integer, is_active boolean NOT NULL DEFAULT true, assigned_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, prospect_id integer, assigned_by character varying);
CREATE TABLE public.campaign_equipment (equipment_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass));
CREATE TABLE public.campaign_fee_values (updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), fee_group_fee_item_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text, fee_item_id integer, value text NOT NULL);
CREATE TABLE public.campaigns (is_active boolean NOT NULL DEFAULT true, pricing_type_id integer, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), created_by character varying, description text, currency text NOT NULL DEFAULT 'USD'::text, name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), equipment text, is_default boolean NOT NULL DEFAULT false, updated_at timestamp without time zone NOT NULL DEFAULT now(), acquirer text NOT NULL);
CREATE TABLE public.data_access_logs (data_volume integer, record_id text, access_type text NOT NULL, field_accessed text, access_reason text, user_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), data_type text NOT NULL, audit_log_id integer, retention_period integer, lawful_basis text, table_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.email_activity (trigger_source character varying, recipient_email character varying NOT NULL, sent_at timestamp without time zone DEFAULT now(), clicked_at timestamp without time zone, recipient_name character varying, template_id integer, metadata jsonb, subject text NOT NULL, error_message text, template_name character varying NOT NULL, opened_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), status character varying NOT NULL, triggered_by character varying);
CREATE TABLE public.email_templates (variables jsonb, text_content text, name character varying NOT NULL, is_active boolean DEFAULT true, category character varying NOT NULL, html_content text NOT NULL, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), description text, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), subject text NOT NULL);
CREATE TABLE public.email_triggers (template_id integer, created_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, is_active boolean DEFAULT true, conditions jsonb, updated_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, description text, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass));
CREATE TABLE public.equipment_items (model_number text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), model text, category text, updated_at timestamp without time zone NOT NULL DEFAULT now(), image_url text, price numeric, created_at timestamp without time zone NOT NULL DEFAULT now(), specifications jsonb DEFAULT '{}'::jsonb, description text, name text NOT NULL, is_active boolean NOT NULL DEFAULT true, manufacturer text, status text DEFAULT 'available'::text, image_data text);
CREATE TABLE public.fee_group_fee_items (fee_item_group_id integer, is_required boolean NOT NULL DEFAULT false, fee_group_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass), fee_item_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_groups (author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), category text, name text NOT NULL, created_by text, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, description text, fees jsonb DEFAULT '{}'::jsonb);
CREATE TABLE public.fee_item_groups (id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, description text, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_items (value_type text NOT NULL, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, fee_item_group_id integer, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text, additional_info text, updated_at timestamp without time zone NOT NULL DEFAULT now(), default_value text, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, description text);
CREATE TABLE public.locations (zip_code text NOT NULL, name text NOT NULL, operating_hours jsonb, status text NOT NULL DEFAULT 'active'::text, phone text, city text NOT NULL, mid character varying, state text NOT NULL, longitude numeric, merchant_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), type text NOT NULL DEFAULT 'store'::text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, address text NOT NULL, email text, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), latitude numeric);
CREATE TABLE public.login_attempts (id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), success boolean NOT NULL, email character varying, ip_address character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), user_agent text, failure_reason character varying, username character varying);
CREATE TABLE public.merchant_prospects (agent_id integer NOT NULL, form_data text, created_at timestamp without time zone NOT NULL DEFAULT now(), notes text, first_name text NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), email text NOT NULL, application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text, validation_token text, validated_at timestamp without time zone, last_name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), current_step integer DEFAULT 0);
CREATE TABLE public.merchants (updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, processing_fee numeric NOT NULL DEFAULT 2.50, email text NOT NULL, status text NOT NULL DEFAULT 'active'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), user_id character varying, website text, business_type text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), business_name text NOT NULL, dba_name text, ein text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, legal_name text, phone text NOT NULL, industry text, agent_id integer);
CREATE TABLE public.pdf_form_fields (validation text, field_label text NOT NULL, field_type text NOT NULL, created_at timestamp without time zone DEFAULT now(), default_value text, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), is_required boolean DEFAULT false, form_id integer NOT NULL, options ARRAY, field_name text NOT NULL, section text, position integer NOT NULL);
CREATE TABLE public.pdf_form_submissions (created_at timestamp without time zone DEFAULT now(), is_public boolean DEFAULT false, data text NOT NULL, updated_at timestamp without time zone DEFAULT now(), status text DEFAULT 'draft'::text, submitted_by text, applicant_email text, form_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), submission_token text NOT NULL);
CREATE TABLE public.pdf_forms (description text, file_size integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), status text DEFAULT 'active'::text, allowed_roles ARRAY DEFAULT '{admin}'::text[], created_at timestamp without time zone DEFAULT now(), file_name text NOT NULL, navigation_title text, show_in_navigation boolean DEFAULT false, uploaded_by text NOT NULL, name text NOT NULL);
CREATE TABLE public.pricing_type_fee_items (is_required boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, fee_item_id integer NOT NULL, pricing_type_id integer NOT NULL);
CREATE TABLE public.pricing_types (description text, created_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL);
CREATE TABLE public.prospect_owners (name text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), email text NOT NULL, ownership_percentage numeric NOT NULL, email_sent boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), prospect_id integer NOT NULL, signature_token text, email_sent_at timestamp without time zone);
CREATE TABLE public.prospect_signatures (signature_type text NOT NULL, prospect_id integer NOT NULL, owner_id integer NOT NULL, signature_token text NOT NULL, signature text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass));
CREATE TABLE public.schema_migrations (checksum character varying NOT NULL, migration_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, name character varying NOT NULL, environment character varying NOT NULL);
CREATE TABLE public.security_events (updated_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb, detected_at timestamp without time zone NOT NULL DEFAULT now(), detected_by text, resolved_at timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), mitigation_actions jsonb, severity text NOT NULL, alert_status text DEFAULT 'new'::text, detection_method text, resolution text, event_type text NOT NULL, audit_log_id integer, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), resolved_by character varying, affected_users jsonb, investigation_notes text, assigned_to character varying);
CREATE TABLE public.sessions (sid character varying NOT NULL, sess jsonb NOT NULL, expire timestamp without time zone NOT NULL);
CREATE TABLE public.transactions (commission_amount numeric DEFAULT 0, commission_rate numeric DEFAULT 0.025, merchant_id integer NOT NULL, status text NOT NULL, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), mid character varying, created_at timestamp without time zone DEFAULT now(), processed_at timestamp with time zone, reference_number text, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, transaction_type text NOT NULL DEFAULT 'payment'::text, payment_method text NOT NULL, net_amount numeric, amount numeric NOT NULL, transaction_id text NOT NULL, processing_fee numeric, location_id integer);
CREATE TABLE public.two_factor_codes (type character varying NOT NULL, code character varying NOT NULL, used boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), expires_at timestamp without time zone NOT NULL, user_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass));
CREATE TABLE public.user_dashboard_preferences (position integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), configuration jsonb DEFAULT '{}'::jsonb, size text NOT NULL DEFAULT 'medium'::text, is_visible boolean NOT NULL DEFAULT true, widget_id text NOT NULL, user_id text NOT NULL);
CREATE TABLE public.users (two_factor_secret character varying, two_factor_enabled boolean DEFAULT false, first_name character varying, username character varying NOT NULL, email_verified boolean DEFAULT false, password_reset_expires timestamp without time zone, created_at timestamp without time zone DEFAULT now(), email_verification_token character varying, password_reset_token character varying, last_name character varying, id character varying NOT NULL, permissions jsonb DEFAULT '{}'::jsonb, last_login_at timestamp without time zone, last_login_ip character varying, status text NOT NULL DEFAULT 'active'::text, profile_image_url character varying, updated_at timestamp without time zone DEFAULT now(), phone character varying NOT NULL DEFAULT ''::character varying, email character varying NOT NULL, password_hash character varying NOT NULL, roles ARRAY NOT NULL, timezone character varying DEFAULT 'UTC'::character varying, communication_preference text NOT NULL DEFAULT 'email'::text);