-- Database backup for development environment
-- Generated at: 2025-08-18T18:02:59.205Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (longitude real, state text NOT NULL, street2 text, timezone text, city text NOT NULL, geo_accuracy real, country text NOT NULL DEFAULT 'US'::text, geocoded_at timestamp without time zone, location_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), type text NOT NULL DEFAULT 'primary'::text, street1 text NOT NULL, postal_code text NOT NULL, latitude real);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), agent_id integer NOT NULL, assigned_by text);
CREATE TABLE public.agents (territory text, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), phone text NOT NULL, email text NOT NULL, last_name text NOT NULL, status text NOT NULL DEFAULT 'active'::text, created_at timestamp without time zone DEFAULT now(), first_name text NOT NULL, user_id character varying NOT NULL, commission_rate numeric DEFAULT 5.00);
CREATE TABLE public.api_keys (contact_email text NOT NULL, is_active boolean DEFAULT true, rate_limit integer DEFAULT 1000, created_at timestamp without time zone NOT NULL DEFAULT now(), organization_name text, key_secret text NOT NULL, name text NOT NULL, key_id text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), last_used_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), expires_at timestamp without time zone);
CREATE TABLE public.api_request_logs (api_key_id integer, method text NOT NULL, user_agent text, ip_address text, response_time integer, response_size integer, error_message text, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), endpoint text NOT NULL, status_code integer NOT NULL, request_size integer);
CREATE TABLE public.audit_logs (user_agent text, severity text DEFAULT 'info'::text, resource text NOT NULL, retention_policy text, notes text, request_body jsonb, application_version text, updated_at timestamp without time zone DEFAULT now(), request_id character varying, new_values jsonb, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), outcome text, response_time integer, risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, error_message text, encryption_key_id character varying, tags jsonb, ip_address text NOT NULL, geolocation jsonb, request_params jsonb, method text, session_id text, environment text DEFAULT 'production'::text, user_id character varying, old_values jsonb, endpoint text, compliance_flags jsonb, action text NOT NULL, device_info jsonb, resource_id text, metadata jsonb, status_code integer, user_email text, data_classification text, resource_type text, details jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), category text);
CREATE TABLE public.business_ownership (id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), form_submission_id integer, signed_at timestamp without time zone, requires_signature boolean NOT NULL DEFAULT false, prospect_id integer, ownership_percentage numeric NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), signature_image_path text, owner_email text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), signature_token text, digital_signature text, signature_type text, owner_name text NOT NULL);
CREATE TABLE public.campaign_assignments (prospect_id integer, campaign_id integer NOT NULL, assigned_by character varying, application_id integer, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), assigned_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_equipment (campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), equipment_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_fee_values (value text NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text);
CREATE TABLE public.campaigns (pricing_type_id integer, name text NOT NULL, created_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), description text, is_default boolean NOT NULL DEFAULT false, acquirer text NOT NULL, equipment text, is_active boolean NOT NULL DEFAULT true, currency text NOT NULL DEFAULT 'USD'::text);
CREATE TABLE public.data_access_logs (data_type text NOT NULL, field_accessed text, record_id text, access_reason text, created_at timestamp without time zone NOT NULL DEFAULT now(), data_volume integer, retention_period integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), access_type text NOT NULL, table_name text NOT NULL, user_id character varying NOT NULL, audit_log_id integer, lawful_basis text);
CREATE TABLE public.email_activity (error_message text, clicked_at timestamp without time zone, template_id integer, triggered_by character varying, metadata jsonb, sent_at timestamp without time zone DEFAULT now(), trigger_source character varying, template_name character varying NOT NULL, opened_at timestamp without time zone, subject text NOT NULL, status character varying NOT NULL, recipient_name character varying, recipient_email character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass));
CREATE TABLE public.email_templates (created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), category character varying NOT NULL, text_content text, html_content text NOT NULL, updated_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, description text, variables jsonb, subject text NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE public.email_triggers (trigger_event character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), description text, conditions jsonb, updated_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, is_active boolean DEFAULT true, template_id integer);
CREATE TABLE public.equipment_items (specifications jsonb DEFAULT '{}'::jsonb, status text DEFAULT 'available'::text, name text NOT NULL, model_number text, manufacturer text, image_data text, is_active boolean NOT NULL DEFAULT true, price numeric, created_at timestamp without time zone NOT NULL DEFAULT now(), category text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), description text, model text, image_url text);
CREATE TABLE public.fee_groups (created_at timestamp without time zone NOT NULL DEFAULT now(), created_by text, name text NOT NULL, description text, display_order integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), category text, fees jsonb DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true, author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass));
CREATE TABLE public.fee_item_groups (display_order integer NOT NULL DEFAULT 0, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, description text, name text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_id integer NOT NULL);
CREATE TABLE public.fee_items (author text NOT NULL DEFAULT 'System'::text, description text, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), fee_item_group_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, value_type text NOT NULL, default_value text, fee_group_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), additional_info text);
CREATE TABLE public.locations (mid character varying, phone text, status text NOT NULL DEFAULT 'active'::text, zip_code text NOT NULL, operating_hours jsonb, email text, longitude numeric, name text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), address text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), merchant_id integer NOT NULL, latitude numeric, state text NOT NULL, type text NOT NULL DEFAULT 'store'::text);
CREATE TABLE public.login_attempts (failure_reason character varying, user_agent text, username character varying, email character varying, success boolean NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), ip_address character varying NOT NULL);
CREATE TABLE public.merchant_prospects (first_name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), form_data text, notes text, current_step integer DEFAULT 0, validation_token text, validated_at timestamp without time zone, last_name text NOT NULL, email text NOT NULL, agent_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text);
CREATE TABLE public.merchants (dba_name text, processing_fee numeric NOT NULL DEFAULT 2.50, business_name text NOT NULL, industry text, email text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'active'::text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), agent_id integer, user_id character varying, business_type text NOT NULL, ein text, website text, phone text NOT NULL, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, legal_name text);
CREATE TABLE public.pdf_form_fields (is_required boolean DEFAULT false, default_value text, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), options ARRAY, position integer NOT NULL, form_id integer NOT NULL, created_at timestamp without time zone DEFAULT now(), validation text, field_type text NOT NULL, section text, field_label text NOT NULL, field_name text NOT NULL);
CREATE TABLE public.pdf_form_submissions (submitted_by text, is_public boolean DEFAULT false, status text DEFAULT 'draft'::text, applicant_email text, submission_token text NOT NULL, data text NOT NULL, form_id integer NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.pdf_forms (file_size integer NOT NULL, status text DEFAULT 'active'::text, show_in_navigation boolean DEFAULT false, description text, uploaded_by text NOT NULL, navigation_title text, file_name text NOT NULL, updated_at timestamp without time zone DEFAULT now(), allowed_roles ARRAY DEFAULT '{admin}'::text[], name text NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass));
CREATE TABLE public.pricing_type_fee_items (fee_item_id integer NOT NULL, pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_required boolean NOT NULL DEFAULT true);
CREATE TABLE public.pricing_types (created_at timestamp without time zone NOT NULL DEFAULT now(), description text, is_active boolean NOT NULL DEFAULT true, name text NOT NULL, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass));
CREATE TABLE public.prospect_owners (email text NOT NULL, email_sent_at timestamp without time zone, signature_token text, name text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email_sent boolean DEFAULT false, ownership_percentage numeric NOT NULL, updated_at timestamp without time zone DEFAULT now(), prospect_id integer NOT NULL, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.prospect_signatures (owner_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), prospect_id integer NOT NULL, signature_token text NOT NULL, signature_type text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), signature text NOT NULL);
CREATE TABLE public.schema_migrations (migration_id character varying NOT NULL, name character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, checksum character varying NOT NULL, environment character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass));
CREATE TABLE public.security_events (resolution text, event_type text NOT NULL, detected_by text, created_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb, detected_at timestamp without time zone NOT NULL DEFAULT now(), investigation_notes text, severity text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), resolved_at timestamp without time zone, mitigation_actions jsonb, detection_method text, affected_users jsonb, audit_log_id integer, alert_status text DEFAULT 'new'::text, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), resolved_by character varying, assigned_to character varying);
CREATE TABLE public.sessions (expire timestamp without time zone NOT NULL, sid character varying NOT NULL, sess jsonb NOT NULL);
CREATE TABLE public.transactions (merchant_id integer NOT NULL, net_amount numeric, commission_rate numeric DEFAULT 0.025, amount numeric NOT NULL, mid character varying, transaction_type text NOT NULL DEFAULT 'payment'::text, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), payment_method text NOT NULL, reference_number text, location_id integer, processing_fee numeric, transaction_id text NOT NULL, commission_amount numeric DEFAULT 0, created_at timestamp without time zone DEFAULT now(), processed_at timestamp with time zone, status text NOT NULL, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.two_factor_codes (created_at timestamp without time zone DEFAULT now(), used boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), expires_at timestamp without time zone NOT NULL, code character varying NOT NULL, type character varying NOT NULL, user_id character varying NOT NULL);
CREATE TABLE public.user_dashboard_preferences (size text NOT NULL DEFAULT 'medium'::text, user_id text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL, widget_id text NOT NULL, position integer NOT NULL DEFAULT 0, configuration jsonb DEFAULT '{}'::jsonb, is_visible boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.users (email_verification_token character varying, last_name character varying, password_reset_expires timestamp without time zone, last_login_ip character varying, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), id character varying NOT NULL, permissions jsonb DEFAULT '{}'::jsonb, last_login_at timestamp without time zone, two_factor_enabled boolean DEFAULT false, username character varying NOT NULL, profile_image_url character varying, email character varying NOT NULL, first_name character varying, password_reset_token character varying, status text NOT NULL DEFAULT 'active'::text, two_factor_secret character varying, timezone character varying DEFAULT 'UTC'::character varying, role text NOT NULL DEFAULT 'merchant'::text, email_verified boolean DEFAULT false, password_hash character varying NOT NULL);