-- Database backup for development environment
-- Generated at: 2025-08-18T17:50:01.750Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), country text NOT NULL DEFAULT 'US'::text, type text NOT NULL DEFAULT 'primary'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), latitude real, geo_accuracy real, longitude real, street2 text, location_id integer NOT NULL, geocoded_at timestamp without time zone, timezone text, postal_code text NOT NULL, street1 text NOT NULL, city text NOT NULL, state text NOT NULL);
CREATE TABLE public.agent_merchants (merchant_id integer NOT NULL, assigned_by text, assigned_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), agent_id integer NOT NULL);
CREATE TABLE public.agents (status text NOT NULL DEFAULT 'active'::text, first_name text NOT NULL, last_name text NOT NULL, phone text NOT NULL, created_at timestamp without time zone DEFAULT now(), email text NOT NULL, territory text, user_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), commission_rate numeric DEFAULT 5.00);
CREATE TABLE public.api_keys (contact_email text NOT NULL, rate_limit integer DEFAULT 1000, expires_at timestamp without time zone, organization_name text, is_active boolean DEFAULT true, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), last_used_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), key_id text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), key_secret text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb);
CREATE TABLE public.api_request_logs (status_code integer NOT NULL, api_key_id integer, endpoint text NOT NULL, response_size integer, user_agent text, request_size integer, ip_address text, created_at timestamp without time zone NOT NULL DEFAULT now(), method text NOT NULL, error_message text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), response_time integer);
CREATE TABLE public.audit_logs (user_agent text, severity text DEFAULT 'info'::text, resource text NOT NULL, retention_policy text, response_time integer, notes text, application_version text, updated_at timestamp without time zone DEFAULT now(), request_body jsonb, request_id character varying, new_values jsonb, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), outcome text, risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, error_message text, encryption_key_id character varying, tags jsonb, ip_address text NOT NULL, geolocation jsonb, request_params jsonb, method text, session_id text, environment text DEFAULT 'production'::text, user_id character varying, old_values jsonb, endpoint text, compliance_flags jsonb, action text NOT NULL, device_info jsonb, resource_id text, metadata jsonb, status_code integer, user_email text, data_classification text, resource_type text, details jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), category text);
CREATE TABLE public.business_ownership (id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), form_submission_id integer, signed_at timestamp without time zone, requires_signature boolean NOT NULL DEFAULT false, prospect_id integer, ownership_percentage numeric NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), signature_image_path text, owner_email text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), signature_token text, digital_signature text, signature_type text, owner_name text NOT NULL);
CREATE TABLE public.campaign_assignments (prospect_id integer, campaign_id integer NOT NULL, assigned_by character varying, application_id integer, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), assigned_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_equipment (campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), equipment_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_fee_values (value text NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text);
CREATE TABLE public.campaigns (pricing_type_id integer, name text NOT NULL, created_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), description text, is_default boolean NOT NULL DEFAULT false, acquirer text NOT NULL, equipment text, is_active boolean NOT NULL DEFAULT true, currency text NOT NULL DEFAULT 'USD'::text);
CREATE TABLE public.data_access_logs (table_name text NOT NULL, user_id character varying NOT NULL, access_reason text, lawful_basis text, field_accessed text, record_id text, retention_period integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), access_type text NOT NULL, data_volume integer, audit_log_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), data_type text NOT NULL);
CREATE TABLE public.email_activity (triggered_by character varying, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), trigger_source character varying, template_id integer, recipient_name character varying, status character varying NOT NULL, sent_at timestamp without time zone DEFAULT now(), metadata jsonb, error_message text, subject text NOT NULL, recipient_email character varying NOT NULL, opened_at timestamp without time zone, template_name character varying NOT NULL, clicked_at timestamp without time zone);
CREATE TABLE public.email_templates (is_active boolean DEFAULT true, variables jsonb, name character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), text_content text, description text, updated_at timestamp without time zone DEFAULT now(), created_at timestamp without time zone DEFAULT now(), html_content text NOT NULL, category character varying NOT NULL, subject text NOT NULL);
CREATE TABLE public.email_triggers (conditions jsonb, description text, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, template_id integer, is_active boolean DEFAULT true);
CREATE TABLE public.equipment_items (manufacturer text, specifications jsonb DEFAULT '{}'::jsonb, name text NOT NULL, image_data text, status text DEFAULT 'available'::text, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), category text, price numeric, image_url text, model_number text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), model text, description text);
CREATE TABLE public.fee_groups (is_active boolean NOT NULL DEFAULT true, created_by text, fees jsonb DEFAULT '{}'::jsonb, name text NOT NULL, description text, display_order integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), category text, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.fee_item_groups (description text, created_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.fee_items (fee_group_id integer NOT NULL, fee_item_group_id integer, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), description text, additional_info text, is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), value_type text NOT NULL, default_value text, name text NOT NULL, author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.locations (mid character varying, phone text, status text NOT NULL DEFAULT 'active'::text, zip_code text NOT NULL, operating_hours jsonb, email text, longitude numeric, name text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), address text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), merchant_id integer NOT NULL, latitude numeric, state text NOT NULL, type text NOT NULL DEFAULT 'store'::text);
CREATE TABLE public.login_attempts (username character varying, success boolean NOT NULL, ip_address character varying NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), user_agent text, email character varying, failure_reason character varying, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.merchant_prospects (email text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), first_name text NOT NULL, agent_id integer NOT NULL, validated_at timestamp without time zone, current_step integer DEFAULT 0, validation_token text, last_name text NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), form_data text, created_at timestamp without time zone NOT NULL DEFAULT now(), application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text, notes text);
CREATE TABLE public.merchants (status text NOT NULL DEFAULT 'active'::text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, phone text NOT NULL, business_name text NOT NULL, industry text, ein text, business_type text NOT NULL, agent_id integer, email text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), user_id character varying, website text, dba_name text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, processing_fee numeric NOT NULL DEFAULT 2.50, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), legal_name text);
CREATE TABLE public.pdf_form_fields (field_name text NOT NULL, section text, is_required boolean DEFAULT false, form_id integer NOT NULL, default_value text, field_type text NOT NULL, validation text, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), options ARRAY, field_label text NOT NULL, created_at timestamp without time zone DEFAULT now(), position integer NOT NULL);
CREATE TABLE public.pdf_form_submissions (created_at timestamp without time zone DEFAULT now(), status text DEFAULT 'draft'::text, data text NOT NULL, updated_at timestamp without time zone DEFAULT now(), applicant_email text, form_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), is_public boolean DEFAULT false, submission_token text NOT NULL, submitted_by text);
CREATE TABLE public.pdf_forms (id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), status text DEFAULT 'active'::text, description text, show_in_navigation boolean DEFAULT false, file_size integer NOT NULL, updated_at timestamp without time zone DEFAULT now(), file_name text NOT NULL, created_at timestamp without time zone DEFAULT now(), navigation_title text, uploaded_by text NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], name text NOT NULL);
CREATE TABLE public.pricing_type_fee_items (is_required boolean NOT NULL DEFAULT true, pricing_type_id integer NOT NULL, fee_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.pricing_types (updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, name text NOT NULL, description text, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.prospect_owners (email_sent_at timestamp without time zone, ownership_percentage numeric NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email_sent boolean DEFAULT false, prospect_id integer NOT NULL, updated_at timestamp without time zone DEFAULT now(), signature_token text, email text NOT NULL, name text NOT NULL);
CREATE TABLE public.prospect_signatures (submitted_at timestamp without time zone DEFAULT now(), prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature_token text NOT NULL, signature_type text NOT NULL, signature text NOT NULL, owner_id integer NOT NULL);
CREATE TABLE public.schema_migrations (migration_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, name character varying NOT NULL, environment character varying NOT NULL, checksum character varying NOT NULL);
CREATE TABLE public.security_events (event_type text NOT NULL, resolved_by character varying, alert_status text DEFAULT 'new'::text, detected_at timestamp without time zone NOT NULL DEFAULT now(), affected_users jsonb, audit_log_id integer, detection_method text, mitigation_actions jsonb, resolved_at timestamp without time zone, detected_by text, investigation_notes text, resolution text, severity text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), assigned_to character varying, affected_resources jsonb, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.sessions (sess jsonb NOT NULL, sid character varying NOT NULL, expire timestamp without time zone NOT NULL);
CREATE TABLE public.transactions (net_amount numeric, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, merchant_id integer NOT NULL, processing_fee numeric, reference_number text, commission_rate numeric DEFAULT 0.025, transaction_id text NOT NULL, mid character varying, amount numeric NOT NULL, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), payment_method text NOT NULL, commission_amount numeric DEFAULT 0, status text NOT NULL);
CREATE TABLE public.two_factor_codes (created_at timestamp without time zone DEFAULT now(), expires_at timestamp without time zone NOT NULL, user_id character varying NOT NULL, type character varying NOT NULL, code character varying NOT NULL, used boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass));
CREATE TABLE public.user_dashboard_preferences (id integer NOT NULL, is_visible boolean NOT NULL DEFAULT true, position integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), size text NOT NULL DEFAULT 'medium'::text, configuration jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), widget_id text NOT NULL, user_id text NOT NULL);
CREATE TABLE public.users (email character varying NOT NULL, last_name character varying, two_factor_secret character varying, last_login_at timestamp without time zone, created_at timestamp without time zone DEFAULT now(), password_reset_expires timestamp without time zone, email_verification_token character varying, first_name character varying, updated_at timestamp without time zone DEFAULT now(), email_verified boolean DEFAULT false, id character varying NOT NULL, role text NOT NULL DEFAULT 'merchant'::text, password_hash character varying NOT NULL, status text NOT NULL DEFAULT 'active'::text, permissions jsonb DEFAULT '{}'::jsonb, two_factor_enabled boolean DEFAULT false, last_login_ip character varying, username character varying NOT NULL, timezone character varying DEFAULT 'UTC'::character varying, profile_image_url character varying, password_reset_token character varying);