-- Database backup for development environment
-- Generated at: 2025-09-26T04:05:16.338Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.acquirer_application_templates (is_active boolean NOT NULL DEFAULT true, acquirer_id integer NOT NULL, version text NOT NULL DEFAULT '1.0'::text, template_name text NOT NULL, pdf_mapping_configuration jsonb, field_configuration jsonb NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), required_fields ARRAY NOT NULL DEFAULT ARRAY[]::text[], conditional_fields jsonb, id integer NOT NULL DEFAULT nextval('acquirer_application_templates_id_seq'::regclass));
CREATE TABLE public.acquirers (code text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), description text, id integer NOT NULL DEFAULT nextval('acquirers_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, is_active boolean NOT NULL DEFAULT true, display_name text NOT NULL);
CREATE TABLE public.addresses (latitude real, longitude real, postal_code text NOT NULL, city text NOT NULL, geocoded_at timestamp without time zone, street1 text NOT NULL, state text NOT NULL, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), location_id integer NOT NULL, geo_accuracy real, timezone text, country text NOT NULL DEFAULT 'US'::text, street2 text, type text NOT NULL DEFAULT 'primary'::text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.agent_merchants (id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), assigned_by text, assigned_at timestamp without time zone DEFAULT now(), merchant_id integer NOT NULL, agent_id integer NOT NULL);
CREATE TABLE public.agents (territory text, phone text NOT NULL, status text NOT NULL DEFAULT 'active'::text, company_id integer, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), last_name text NOT NULL, commission_rate numeric DEFAULT 5.00, user_id character varying NOT NULL, first_name text NOT NULL, email text NOT NULL);
CREATE TABLE public.api_keys (key_id text NOT NULL, rate_limit integer DEFAULT 1000, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), last_used_at timestamp without time zone, is_active boolean DEFAULT true, key_secret text NOT NULL, name text NOT NULL, expires_at timestamp without time zone, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), contact_email text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), organization_name text);
CREATE TABLE public.api_request_logs (api_key_id integer, ip_address text, status_code integer NOT NULL, response_time integer, created_at timestamp without time zone NOT NULL DEFAULT now(), error_message text, endpoint text NOT NULL, user_agent text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), request_size integer, response_size integer, method text NOT NULL);
CREATE TABLE public.audit_logs (action text NOT NULL, tags jsonb, details jsonb, severity text DEFAULT 'info'::text, risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, request_body jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), request_params jsonb, notes text, resource_id text, error_message text, resource_type text, category text, method text, compliance_flags jsonb, metadata jsonb, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), encryption_key_id character varying, status_code integer, device_info jsonb, ip_address text NOT NULL, application_version text, user_email text, data_classification text, user_id character varying, request_id character varying, environment text DEFAULT 'production'::text, resource text NOT NULL, endpoint text, new_values jsonb, outcome text, session_id text, old_values jsonb, retention_policy text, created_at timestamp without time zone NOT NULL DEFAULT now(), response_time integer, geolocation jsonb, user_agent text, updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.business_ownership (signature_image_path text, digital_signature text, requires_signature boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), owner_email text NOT NULL, prospect_id integer, signature_type text, signature_token text, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), form_submission_id integer, owner_name text NOT NULL, ownership_percentage numeric NOT NULL, signed_at timestamp without time zone);
CREATE TABLE public.campaign_assignments (assigned_by character varying, campaign_id integer NOT NULL, assigned_at timestamp without time zone NOT NULL DEFAULT now(), prospect_id integer, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), application_id integer);
CREATE TABLE public.campaign_equipment (id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_required boolean NOT NULL DEFAULT false, display_order integer NOT NULL DEFAULT 0, campaign_id integer NOT NULL, equipment_item_id integer NOT NULL);
CREATE TABLE public.campaign_fee_values (id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), fee_group_fee_item_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), value text NOT NULL, campaign_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer, value_type text NOT NULL DEFAULT 'percentage'::text);
CREATE TABLE public.campaigns (is_active boolean NOT NULL DEFAULT true, name text NOT NULL, created_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), pricing_type_id integer, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), description text, acquirer text NOT NULL, acquirer_id integer, currency text NOT NULL DEFAULT 'USD'::text, is_default boolean NOT NULL DEFAULT false, equipment text);
CREATE TABLE public.companies (industry text, website text, name text NOT NULL, id integer NOT NULL DEFAULT nextval('companies_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, tax_id character varying, business_type text, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, description text, phone text, status text NOT NULL DEFAULT 'active'::text, email text, address jsonb, logo_url text);
CREATE TABLE public.data_access_logs (access_type text NOT NULL, table_name text NOT NULL, retention_period integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), data_volume integer, access_reason text, record_id text, audit_log_id integer, data_type text NOT NULL, user_id character varying NOT NULL, lawful_basis text, field_accessed text);
CREATE TABLE public.email_activity (error_message text, subject text NOT NULL, metadata jsonb, trigger_source character varying, status character varying NOT NULL, recipient_name character varying, triggered_by character varying, opened_at timestamp without time zone, template_name character varying NOT NULL, template_id integer, recipient_email character varying NOT NULL, sent_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), clicked_at timestamp without time zone);
CREATE TABLE public.email_templates (description text, html_content text NOT NULL, category character varying NOT NULL, is_active boolean DEFAULT true, text_content text, name character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), subject text NOT NULL, variables jsonb, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass));
CREATE TABLE public.email_triggers (is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), description text, trigger_event character varying NOT NULL, conditions jsonb, template_id integer);
CREATE TABLE public.equipment_items (specifications jsonb DEFAULT '{}'::jsonb, name text NOT NULL, image_data text, image_url text, status text DEFAULT 'available'::text, is_active boolean NOT NULL DEFAULT true, description text, category text, created_at timestamp without time zone NOT NULL DEFAULT now(), price numeric, updated_at timestamp without time zone NOT NULL DEFAULT now(), model_number text, manufacturer text, model text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass));
CREATE TABLE public.fee_group_fee_items (fee_item_id integer NOT NULL, fee_group_id integer NOT NULL, is_required boolean NOT NULL DEFAULT false, fee_item_group_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass));
CREATE TABLE public.fee_groups (name text NOT NULL, fees jsonb DEFAULT '{}'::jsonb, category text, created_at timestamp without time zone NOT NULL DEFAULT now(), description text, updated_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text, is_active boolean NOT NULL DEFAULT true, created_by text);
CREATE TABLE public.fee_item_groups (author text NOT NULL DEFAULT 'System'::text, name text NOT NULL, is_active boolean NOT NULL DEFAULT true, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), fee_group_id integer NOT NULL, description text, created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0);
CREATE TABLE public.fee_items (default_value text, description text, additional_info text, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), name text NOT NULL, fee_item_group_id integer, display_order integer NOT NULL DEFAULT 0, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), value_type text NOT NULL);
CREATE TABLE public.locations (address text NOT NULL, merchant_id integer NOT NULL, type text NOT NULL DEFAULT 'store'::text, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), operating_hours jsonb, status text NOT NULL DEFAULT 'active'::text, latitude numeric, name text NOT NULL, zip_code text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, longitude numeric, state text NOT NULL, phone text, email text, mid character varying);
CREATE TABLE public.login_attempts (success boolean NOT NULL, user_agent text, email character varying, ip_address character varying NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), failure_reason character varying, username character varying, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.merchant_prospects (validation_token text, email text NOT NULL, first_name text NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text, validated_at timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), agent_id integer NOT NULL, notes text, current_step integer DEFAULT 0, form_data text, updated_at timestamp without time zone NOT NULL DEFAULT now(), last_name text NOT NULL);
CREATE TABLE public.merchants (created_at timestamp without time zone NOT NULL DEFAULT now(), agent_id integer, company_id integer, business_type text NOT NULL, status text NOT NULL DEFAULT 'active'::text, processing_fee numeric NOT NULL DEFAULT 2.50, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), website text, business_name text NOT NULL, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, email text NOT NULL, user_id character varying, phone text NOT NULL, legal_name text, dba_name text, ein text, industry text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.pdf_form_fields (is_required boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), field_type text NOT NULL, position integer NOT NULL, field_label text NOT NULL, created_at timestamp without time zone DEFAULT now(), field_name text NOT NULL, validation text, form_id integer NOT NULL, options ARRAY, section text, default_value text);
CREATE TABLE public.pdf_form_submissions (is_public boolean DEFAULT false, updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, submitted_by text, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), submission_token text NOT NULL, data text NOT NULL, status text DEFAULT 'draft'::text, applicant_email text);
CREATE TABLE public.pdf_forms (file_name text NOT NULL, created_at timestamp without time zone DEFAULT now(), name text NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], updated_at timestamp without time zone DEFAULT now(), file_size integer NOT NULL, status text DEFAULT 'active'::text, show_in_navigation boolean DEFAULT false, description text, uploaded_by text NOT NULL, navigation_title text, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass));
CREATE TABLE public.pricing_type_fee_items (is_required boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, fee_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), pricing_type_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.pricing_types (description text, updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.prospect_applications (id integer NOT NULL DEFAULT nextval('prospect_applications_id_seq'::regclass), rejected_at timestamp without time zone, template_version text NOT NULL, template_id integer NOT NULL, rejection_reason text, prospect_id integer NOT NULL, acquirer_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), approved_at timestamp without time zone, generated_pdf_path text, application_data jsonb NOT NULL DEFAULT '{}'::jsonb, submitted_at timestamp without time zone, status text NOT NULL DEFAULT 'draft'::text);
CREATE TABLE public.prospect_owners (updated_at timestamp without time zone DEFAULT now(), name text NOT NULL, created_at timestamp without time zone DEFAULT now(), email_sent_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email text NOT NULL, prospect_id integer NOT NULL, ownership_percentage numeric NOT NULL, email_sent boolean DEFAULT false, signature_token text);
CREATE TABLE public.prospect_signatures (submitted_at timestamp without time zone DEFAULT now(), owner_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature text NOT NULL, signature_type text NOT NULL, signature_token text NOT NULL, prospect_id integer NOT NULL);
CREATE TABLE public.schema_migrations (checksum character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, environment character varying NOT NULL, migration_id character varying NOT NULL, name character varying NOT NULL);
CREATE TABLE public.security_events (resolved_by character varying, affected_resources jsonb, detected_at timestamp without time zone NOT NULL DEFAULT now(), severity text NOT NULL, affected_users jsonb, detection_method text, resolution text, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), event_type text NOT NULL, investigation_notes text, assigned_to character varying, created_at timestamp without time zone NOT NULL DEFAULT now(), resolved_at timestamp without time zone, mitigation_actions jsonb, audit_log_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), detected_by text, alert_status text DEFAULT 'new'::text);
CREATE TABLE public.sessions (sid character varying NOT NULL, sess jsonb NOT NULL, expire timestamp without time zone NOT NULL);
CREATE TABLE public.transactions (amount numeric NOT NULL, reference_number text, status text NOT NULL, processed_at timestamp with time zone, commission_rate numeric DEFAULT 0.025, created_at timestamp without time zone DEFAULT now(), location_id integer, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), commission_amount numeric DEFAULT 0, net_amount numeric, mid character varying, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, transaction_id text NOT NULL, processing_fee numeric, transaction_type text NOT NULL DEFAULT 'payment'::text, payment_method text NOT NULL, merchant_id integer NOT NULL);
CREATE TABLE public.two_factor_codes (type character varying NOT NULL, expires_at timestamp without time zone NOT NULL, used boolean DEFAULT false, user_id character varying NOT NULL, code character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass));
CREATE TABLE public.user_dashboard_preferences (user_id text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), position integer NOT NULL DEFAULT 0, id integer NOT NULL, configuration jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), widget_id text NOT NULL, size text NOT NULL DEFAULT 'medium'::text, is_visible boolean NOT NULL DEFAULT true);
CREATE TABLE public.users (password_reset_expires timestamp without time zone, permissions jsonb DEFAULT '{}'::jsonb, timezone character varying DEFAULT 'UTC'::character varying, last_login_ip character varying, email_verification_token character varying, last_name character varying, created_at timestamp without time zone DEFAULT now(), communication_preference text NOT NULL DEFAULT 'email'::text, phone text NOT NULL DEFAULT ''::character varying, password_hash character varying NOT NULL, email_verified boolean DEFAULT false, two_factor_secret character varying, first_name character varying, updated_at timestamp without time zone DEFAULT now(), last_login_at timestamp without time zone, id character varying NOT NULL, email character varying NOT NULL, two_factor_enabled boolean DEFAULT false, username character varying NOT NULL, profile_image_url character varying, status text NOT NULL DEFAULT 'active'::text, password_reset_token character varying, roles ARRAY NOT NULL);