-- Database backup for production environment
-- Generated at: 2025-09-26T03:31:58.657Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.acquirer_application_templates (field_configuration jsonb NOT NULL, pdf_mapping_configuration jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), required_fields ARRAY NOT NULL DEFAULT ARRAY[]::text[], version text NOT NULL DEFAULT '1.0'::text, acquirer_id integer NOT NULL, template_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), conditional_fields jsonb, id integer NOT NULL DEFAULT nextval('acquirer_application_templates_id_seq'::regclass), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.acquirers (is_active boolean NOT NULL DEFAULT true, description text, name text NOT NULL, code text NOT NULL, display_name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('acquirers_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.addresses (geo_accuracy real, street2 text, geocoded_at timestamp without time zone, type text NOT NULL DEFAULT 'primary'::text, state text NOT NULL, longitude real, timezone text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), country text NOT NULL DEFAULT 'US'::text, street1 text NOT NULL, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), location_id integer NOT NULL, postal_code text NOT NULL, latitude real);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), agent_id integer NOT NULL, merchant_id integer NOT NULL, assigned_by text, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass));
CREATE TABLE public.agents (id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), commission_rate numeric DEFAULT 5.00, status text NOT NULL DEFAULT 'active'::text, last_name text NOT NULL, company_id integer, phone text NOT NULL, first_name text NOT NULL, email text NOT NULL, user_id character varying NOT NULL, territory text);
CREATE TABLE public.api_keys (last_used_at timestamp without time zone, rate_limit integer DEFAULT 1000, expires_at timestamp without time zone, key_id text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), organization_name text, updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, is_active boolean DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), key_secret text NOT NULL, contact_email text NOT NULL);
CREATE TABLE public.api_request_logs (response_time integer, status_code integer NOT NULL, api_key_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), ip_address text, response_size integer, error_message text, user_agent text, request_size integer, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), method text NOT NULL, endpoint text NOT NULL);
CREATE TABLE public.audit_logs (geolocation jsonb, resource_id text, response_time integer, created_at timestamp without time zone DEFAULT now(), data_classification text, resource text, application_version text DEFAULT 'v1.0.0'::text, endpoint text, compliance_flags ARRAY, device_info jsonb, error_message text, timestamp timestamp without time zone NOT NULL DEFAULT now(), environment text DEFAULT 'development'::text, notes text, request_params jsonb, resource_type text, request_body jsonb, retention_policy text, outcome text, method text, risk_level text DEFAULT 'medium'::text, category text, session_id text, old_values jsonb, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), encryption_key_id character varying, tags ARRAY, request_id character varying, severity text DEFAULT 'info'::text, action text NOT NULL, new_values jsonb, user_id character varying, correlation_id character varying, ip_address text NOT NULL, user_email text, user_agent text, details jsonb, status_code integer, metadata jsonb);
CREATE TABLE public.business_ownership (form_submission_id integer, signed_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), owner_name text NOT NULL, ownership_percentage numeric NOT NULL, digital_signature text, requires_signature boolean NOT NULL DEFAULT false, prospect_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), owner_email text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), signature_image_path text, signature_type text, signature_token text);
CREATE TABLE public.campaign_assignments (id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), assigned_by character varying, campaign_id integer NOT NULL, prospect_id integer, application_id integer, is_active boolean NOT NULL DEFAULT true, assigned_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_equipment (is_required boolean NOT NULL DEFAULT false, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), equipment_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), campaign_id integer NOT NULL);
CREATE TABLE public.campaign_fee_values (id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), campaign_id integer NOT NULL, value text NOT NULL, fee_item_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_fee_item_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), value_type text NOT NULL DEFAULT 'percentage'::text);
CREATE TABLE public.campaigns (acquirer_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), name text NOT NULL, equipment text, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), currency text NOT NULL DEFAULT 'USD'::text, is_default boolean NOT NULL DEFAULT false, pricing_type_id integer, created_by character varying, is_active boolean NOT NULL DEFAULT true, description text, acquirer text);
CREATE TABLE public.companies (phone text, settings jsonb DEFAULT '{}'::jsonb, website text, updated_at timestamp without time zone NOT NULL DEFAULT now(), address jsonb, description text, status text NOT NULL DEFAULT 'active'::text, name text NOT NULL, logo_url text, industry text, tax_id character varying, business_type text, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('companies_id_seq'::regclass), email text);
CREATE TABLE public.data_access_logs (lawful_basis text, field_accessed text, table_name text NOT NULL, record_id text, user_id character varying NOT NULL, access_reason text, access_type text NOT NULL, retention_period integer, audit_log_id integer, data_type text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), data_volume integer);
CREATE TABLE public.email_activity (clicked_at timestamp without time zone, subject text NOT NULL, recipient_name character varying, template_id integer, trigger_source character varying, template_name character varying NOT NULL, status character varying NOT NULL, sent_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), triggered_by character varying, opened_at timestamp without time zone, error_message text, recipient_email character varying NOT NULL, metadata jsonb);
CREATE TABLE public.email_templates (description text, name character varying NOT NULL, variables jsonb, is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), text_content text, created_at timestamp without time zone DEFAULT now(), html_content text NOT NULL, subject text NOT NULL, updated_at timestamp without time zone DEFAULT now(), category character varying NOT NULL);
CREATE TABLE public.email_triggers (template_id integer, name character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, is_active boolean DEFAULT true, description text, created_at timestamp without time zone DEFAULT now(), conditions jsonb, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass));
CREATE TABLE public.equipment_items (image_data text, specifications jsonb DEFAULT '{}'::jsonb, description text, model_number text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, model text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), price numeric, status text DEFAULT 'available'::text, category text, manufacturer text, is_active boolean NOT NULL DEFAULT true, image_url text, name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.fee_group_fee_items (is_required boolean NOT NULL DEFAULT false, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass), fee_item_id integer NOT NULL, fee_item_group_id integer, fee_group_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_groups (category text, description text, is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, display_order integer DEFAULT 0, author text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fees jsonb DEFAULT '{}'::jsonb, created_by text);
CREATE TABLE public.fee_item_groups (is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), description text, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, display_order integer NOT NULL DEFAULT 0, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, name text NOT NULL, fee_group_id integer NOT NULL);
CREATE TABLE public.fee_items (default_value text, name text NOT NULL, value_type text NOT NULL, display_order integer NOT NULL DEFAULT 0, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fee_item_group_id integer, description text, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), is_active boolean NOT NULL DEFAULT true, additional_info text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.locations (id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), latitude numeric, name text NOT NULL, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, type text NOT NULL DEFAULT 'store'::text, mid character varying, zip_code text NOT NULL, city text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, status text DEFAULT 'active'::text, address text NOT NULL, merchant_id integer, email text, longitude numeric, operating_hours jsonb, state text NOT NULL, phone text);
CREATE TABLE public.login_attempts (user_agent text, success boolean NOT NULL, created_at timestamp without time zone DEFAULT now(), username character varying, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), ip_address character varying NOT NULL, failure_reason character varying, email character varying);
CREATE TABLE public.merchant_prospects (updated_at timestamp without time zone NOT NULL DEFAULT now(), current_step integer DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), validated_at timestamp without time zone, last_name text NOT NULL, validation_token text, first_name text NOT NULL, application_started_at timestamp without time zone, form_data text, notes text, agent_id integer NOT NULL, email text NOT NULL, status text NOT NULL DEFAULT 'pending'::text);
CREATE TABLE public.merchants (agent_id integer, ein text, business_name text NOT NULL, phone text, email text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, user_id text, legal_name text, industry text, dba_name text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, processing_fee numeric NOT NULL DEFAULT 2.50, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, status text DEFAULT 'pending'::text, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), company_id integer, business_type text, website text);
CREATE TABLE public.pdf_form_fields (field_name text NOT NULL, field_label text NOT NULL, options ARRAY, default_value text, validation text, position integer NOT NULL, is_required boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), section text, form_id integer NOT NULL, field_type text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass));
CREATE TABLE public.pdf_form_submissions (is_public boolean DEFAULT false, status text DEFAULT 'draft'::text, created_at timestamp without time zone DEFAULT now(), data text NOT NULL, applicant_email text, submission_token text NOT NULL, submitted_by text, updated_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), form_id integer NOT NULL);
CREATE TABLE public.pdf_forms (navigation_title text, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), allowed_roles ARRAY DEFAULT '{admin}'::text[], updated_at timestamp without time zone DEFAULT now(), file_size integer NOT NULL, file_name text NOT NULL, show_in_navigation boolean DEFAULT false, uploaded_by text NOT NULL, status text DEFAULT 'active'::text, description text, name text NOT NULL);
CREATE TABLE public.pricing_type_fee_items (created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), fee_item_id integer NOT NULL, pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT true);
CREATE TABLE public.pricing_types (author text NOT NULL DEFAULT 'System'::text, description text, is_active boolean NOT NULL DEFAULT true, name text NOT NULL, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.prospect_applications (submitted_at timestamp without time zone, status text NOT NULL DEFAULT 'draft'::text, application_data jsonb NOT NULL DEFAULT '{}'::jsonb, approved_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), acquirer_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_applications_id_seq'::regclass), template_id integer NOT NULL, prospect_id integer NOT NULL, generated_pdf_path text, rejected_at timestamp without time zone, rejection_reason text, template_version text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.prospect_owners (ownership_percentage numeric NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email text NOT NULL, signature_token text, name text NOT NULL, email_sent_at timestamp without time zone, prospect_id integer NOT NULL, email_sent boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.prospect_signatures (prospect_id integer NOT NULL, submitted_at timestamp without time zone DEFAULT now(), signature text NOT NULL, signature_type text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature_token text NOT NULL, owner_id integer NOT NULL);
CREATE TABLE public.schema_migrations (applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, name character varying NOT NULL, checksum character varying NOT NULL, migration_id character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), environment character varying NOT NULL);
CREATE TABLE public.security_events (affected_users jsonb, severity text NOT NULL, mitigation_actions jsonb, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), event_type text NOT NULL, detected_at timestamp without time zone NOT NULL DEFAULT now(), assigned_to character varying, created_at timestamp without time zone NOT NULL DEFAULT now(), resolution text, audit_log_id integer, resolved_at timestamp without time zone, investigation_notes text, updated_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb, alert_status text DEFAULT 'new'::text, resolved_by character varying, detected_by text, detection_method text);
CREATE TABLE public.sessions (sid character varying NOT NULL, expire timestamp without time zone NOT NULL, sess json NOT NULL);
CREATE TABLE public.transactions (reference_number text, status text DEFAULT 'pending'::text, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), net_amount numeric DEFAULT 0, mid character varying, payment_method text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, transaction_id text NOT NULL DEFAULT ''::text, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, merchant_id integer, amount numeric NOT NULL, transaction_type text NOT NULL, commission_amount numeric DEFAULT 0, processed_at timestamp with time zone, commission_rate numeric DEFAULT 0.025, location_id integer, processing_fee numeric DEFAULT 0);
CREATE TABLE public.two_factor_codes (id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), user_id character varying NOT NULL, code character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), expires_at timestamp without time zone NOT NULL, used boolean DEFAULT false, type character varying NOT NULL);
CREATE TABLE public.user_company_associations (updated_at timestamp without time zone NOT NULL DEFAULT now(), permissions jsonb DEFAULT '{}'::jsonb, user_id character varying NOT NULL, is_primary boolean NOT NULL DEFAULT false, start_date timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('user_company_associations_id_seq'::regclass), end_date timestamp without time zone, is_active boolean NOT NULL DEFAULT true, company_id integer NOT NULL, department text, company_role text NOT NULL, title text);
CREATE TABLE public.user_dashboard_preferences (widget_id text NOT NULL, id integer NOT NULL, user_id text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), position integer NOT NULL DEFAULT 0, is_visible boolean NOT NULL DEFAULT true, size text NOT NULL DEFAULT 'medium'::text, configuration jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.users (last_login_ip character varying, timezone character varying DEFAULT 'UTC'::character varying, roles ARRAY DEFAULT '{merchant}'::text[], email_verified boolean DEFAULT false, permissions jsonb DEFAULT '{}'::jsonb, communication_preference text NOT NULL DEFAULT 'email'::text, password_hash character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), email_verification_token character varying, two_factor_enabled boolean DEFAULT false, phone text NOT NULL DEFAULT ''::character varying, email character varying NOT NULL, last_login_at timestamp without time zone, profile_image_url character varying, password_reset_expires timestamp without time zone, status text NOT NULL DEFAULT 'active'::text, password_reset_token character varying, last_name character varying, two_factor_secret character varying, updated_at timestamp without time zone DEFAULT now(), id character varying NOT NULL, first_name character varying, username character varying NOT NULL);