-- Database backup for production environment
-- Generated at: 2025-08-18T18:06:08.834Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (street2 text, geocoded_at timestamp without time zone, type text NOT NULL DEFAULT 'primary'::text, street1 text NOT NULL, city text NOT NULL, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), state text NOT NULL, geo_accuracy real, postal_code text NOT NULL, latitude real, country text NOT NULL DEFAULT 'US'::text, longitude real, location_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), timezone text);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), agent_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), merchant_id integer NOT NULL, assigned_by text);
CREATE TABLE public.agents (commission_rate numeric DEFAULT 5.00, created_at timestamp without time zone DEFAULT now(), last_name text NOT NULL, user_id character varying NOT NULL, territory text, first_name text NOT NULL, status text NOT NULL DEFAULT 'active'::text, phone text NOT NULL, email text NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass));
CREATE TABLE public.api_keys (last_used_at timestamp without time zone, key_secret text NOT NULL, key_id text NOT NULL, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), contact_email text NOT NULL, name text NOT NULL, organization_name text, updated_at timestamp without time zone NOT NULL DEFAULT now(), permissions jsonb NOT NULL DEFAULT '[]'::jsonb, created_at timestamp without time zone NOT NULL DEFAULT now(), rate_limit integer DEFAULT 1000, expires_at timestamp without time zone, is_active boolean DEFAULT true);
CREATE TABLE public.api_request_logs (method text NOT NULL, endpoint text NOT NULL, request_size integer, error_message text, user_agent text, status_code integer NOT NULL, api_key_id integer, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), response_size integer, response_time integer, ip_address text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.audit_logs (outcome text, resource text, tags ARRAY, request_body jsonb, retention_policy text, resource_id text, response_time integer, new_values jsonb, error_message text, metadata jsonb, session_id text, request_id character varying, updated_at timestamp without time zone DEFAULT now(), notes text, ip_address text NOT NULL, application_version text DEFAULT 'v1.0.0'::text, user_email text, status_code integer, correlation_id character varying, geolocation jsonb, created_at timestamp without time zone DEFAULT now(), timestamp timestamp without time zone NOT NULL DEFAULT now(), data_classification text, device_info jsonb, category text, environment text DEFAULT 'development'::text, resource_type text, old_values jsonb, risk_level text DEFAULT 'medium'::text, user_id character varying, encryption_key_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), action text NOT NULL, method text, request_params jsonb, user_agent text, severity text DEFAULT 'info'::text, details jsonb, endpoint text, compliance_flags ARRAY);
CREATE TABLE public.business_ownership (id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), signature_type text, signature_token text, form_submission_id integer, owner_email text NOT NULL, signed_at timestamp without time zone, owner_name text NOT NULL, ownership_percentage numeric NOT NULL, requires_signature boolean NOT NULL DEFAULT false, signature_image_path text, created_at timestamp without time zone NOT NULL DEFAULT now(), digital_signature text, prospect_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_assignments (assigned_by character varying, is_active boolean NOT NULL DEFAULT true, application_id integer, prospect_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass));
CREATE TABLE public.campaign_equipment (campaign_id integer NOT NULL, equipment_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_required boolean NOT NULL DEFAULT false, display_order integer NOT NULL DEFAULT 0);
CREATE TABLE public.campaign_fee_values (created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), value text NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text);
CREATE TABLE public.campaigns (updated_at timestamp without time zone NOT NULL DEFAULT now(), is_default boolean NOT NULL DEFAULT false, acquirer text NOT NULL, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), created_by character varying, currency text NOT NULL DEFAULT 'USD'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), pricing_type_id integer, equipment text, is_active boolean NOT NULL DEFAULT true, name text NOT NULL, description text);
CREATE TABLE public.data_access_logs (lawful_basis text, access_type text NOT NULL, record_id text, access_reason text, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), data_volume integer, table_name text NOT NULL, user_id character varying NOT NULL, retention_period integer, audit_log_id integer, data_type text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), field_accessed text);
CREATE TABLE public.email_activity (subject text NOT NULL, status character varying NOT NULL, recipient_name character varying, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), template_id integer, error_message text, sent_at timestamp without time zone DEFAULT now(), triggered_by character varying, metadata jsonb, recipient_email character varying NOT NULL, clicked_at timestamp without time zone, trigger_source character varying, opened_at timestamp without time zone, template_name character varying NOT NULL);
CREATE TABLE public.email_templates (is_active boolean DEFAULT true, subject text NOT NULL, variables jsonb, updated_at timestamp without time zone DEFAULT now(), category character varying NOT NULL, html_content text NOT NULL, text_content text, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), description text, name character varying NOT NULL);
CREATE TABLE public.email_triggers (template_id integer, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, conditions jsonb, created_at timestamp without time zone DEFAULT now(), description text, name character varying NOT NULL, is_active boolean DEFAULT true);
CREATE TABLE public.equipment_items (model_number text, price numeric, image_data text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, specifications jsonb DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true, status text DEFAULT 'available'::text, name text NOT NULL, model text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, image_url text, category text, description text, manufacturer text);
CREATE TABLE public.fee_groups (updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_by text, is_active boolean DEFAULT true, fees jsonb DEFAULT '{}'::jsonb, name text NOT NULL, author text, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, description text, display_order integer DEFAULT 0, category text);
CREATE TABLE public.fee_item_groups (fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), description text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.fee_items (is_active boolean NOT NULL DEFAULT true, default_value text, fee_item_group_id integer, display_order integer NOT NULL DEFAULT 0, description text, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, additional_info text, name text NOT NULL, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, value_type text NOT NULL);
CREATE TABLE public.locations (mid character varying, address text NOT NULL, name text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, city text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, operating_hours jsonb, phone text, zip_code text NOT NULL, latitude numeric, type text NOT NULL DEFAULT 'store'::text, state text NOT NULL, email text, merchant_id integer, longitude numeric, status text DEFAULT 'active'::text);
CREATE TABLE public.login_attempts (created_at timestamp without time zone DEFAULT now(), failure_reason character varying, success boolean NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), username character varying, user_agent text, ip_address character varying NOT NULL, email character varying);
CREATE TABLE public.merchant_prospects (email text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), notes text, first_name text NOT NULL, form_data text, last_name text NOT NULL, validated_at timestamp without time zone, current_step integer DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), application_started_at timestamp without time zone, status text NOT NULL DEFAULT 'pending'::text, validation_token text, agent_id integer NOT NULL);
CREATE TABLE public.merchants (email text NOT NULL, status text DEFAULT 'pending'::text, business_name text NOT NULL, processing_fee numeric NOT NULL DEFAULT 2.50, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), monthly_volume numeric NOT NULL DEFAULT '0'::numeric, user_id text, ein text, website text, legal_name text, agent_id integer, industry text, dba_name text, business_type text, phone text);
CREATE TABLE public.pdf_form_fields (form_id integer NOT NULL, validation text, default_value text, field_label text NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), position integer NOT NULL, is_required boolean DEFAULT false, field_type text NOT NULL, options ARRAY, field_name text NOT NULL, section text);
CREATE TABLE public.pdf_form_submissions (created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), form_id integer NOT NULL, updated_at timestamp without time zone DEFAULT now(), is_public boolean DEFAULT false, submission_token text NOT NULL, submitted_by text, data text NOT NULL, status text DEFAULT 'draft'::text, applicant_email text);
CREATE TABLE public.pdf_forms (allowed_roles ARRAY DEFAULT '{admin}'::text[], file_name text NOT NULL, name text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), navigation_title text, uploaded_by text NOT NULL, show_in_navigation boolean DEFAULT false, description text, file_size integer NOT NULL, status text DEFAULT 'active'::text, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.pricing_type_fee_items (pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), is_required boolean NOT NULL DEFAULT true, fee_item_id integer NOT NULL);
CREATE TABLE public.pricing_types (id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, author text NOT NULL DEFAULT 'System'::text, description text, is_active boolean NOT NULL DEFAULT true, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.prospect_owners (prospect_id integer NOT NULL, ownership_percentage numeric NOT NULL, signature_token text, email_sent_at timestamp without time zone, updated_at timestamp without time zone DEFAULT now(), email_sent boolean DEFAULT false, name text NOT NULL, email text NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass));
CREATE TABLE public.prospect_signatures (id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature text NOT NULL, owner_id integer NOT NULL, signature_type text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), signature_token text NOT NULL, prospect_id integer NOT NULL);
CREATE TABLE public.schema_migrations (id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), migration_id character varying NOT NULL, checksum character varying NOT NULL, environment character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, name character varying NOT NULL);
CREATE TABLE public.security_events (affected_resources jsonb, severity text NOT NULL, detection_method text, mitigation_actions jsonb, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), affected_users jsonb, event_type text NOT NULL, detected_at timestamp without time zone NOT NULL DEFAULT now(), assigned_to character varying, created_at timestamp without time zone NOT NULL DEFAULT now(), resolution text, audit_log_id integer, resolved_at timestamp without time zone, investigation_notes text, updated_at timestamp without time zone NOT NULL DEFAULT now(), alert_status text DEFAULT 'new'::text, resolved_by character varying, detected_by text);
CREATE TABLE public.sessions (expire timestamp without time zone NOT NULL, sess json NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (payment_method text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, transaction_type text NOT NULL, reference_number text, commission_rate numeric DEFAULT 0.025, processing_fee numeric DEFAULT 0, amount numeric NOT NULL, commission_amount numeric DEFAULT 0, processed_at timestamp with time zone, merchant_id integer, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), net_amount numeric DEFAULT 0, location_id integer, status text DEFAULT 'pending'::text);
CREATE TABLE public.two_factor_codes (created_at timestamp without time zone DEFAULT now(), used boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), user_id character varying NOT NULL, expires_at timestamp without time zone NOT NULL, code character varying NOT NULL, type character varying NOT NULL);
CREATE TABLE public.user_dashboard_preferences (updated_at timestamp without time zone NOT NULL DEFAULT now(), is_visible boolean NOT NULL DEFAULT true, configuration jsonb DEFAULT '{}'::jsonb, position integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), user_id text NOT NULL, id integer NOT NULL, widget_id text NOT NULL, size text NOT NULL DEFAULT 'medium'::text);
CREATE TABLE public.users (profile_image_url character varying, created_at timestamp without time zone DEFAULT now(), two_factor_enabled boolean DEFAULT false, last_login_at timestamp without time zone, email character varying NOT NULL, password_hash character varying NOT NULL, two_factor_secret character varying, id character varying NOT NULL, password_reset_expires timestamp without time zone, password_reset_token character varying, email_verified boolean DEFAULT false, status text NOT NULL DEFAULT 'active'::text, updated_at timestamp without time zone DEFAULT now(), last_login_ip character varying, first_name character varying, timezone character varying DEFAULT 'UTC'::character varying, permissions jsonb DEFAULT '{}'::jsonb, email_verification_token character varying, role text NOT NULL DEFAULT 'merchant'::text, username character varying NOT NULL, last_name character varying);