-- Database backup for production environment
-- Generated at: 2025-08-18T17:53:47.415Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (country text NOT NULL DEFAULT 'US'::text, type text NOT NULL DEFAULT 'primary'::text, geocoded_at timestamp without time zone, timezone text, created_at timestamp without time zone NOT NULL DEFAULT now(), street2 text, latitude real, geo_accuracy real, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), location_id integer NOT NULL, state text NOT NULL, street1 text NOT NULL, longitude real, postal_code text NOT NULL, city text NOT NULL);
CREATE TABLE public.agent_merchants (agent_id integer NOT NULL, assigned_at timestamp without time zone DEFAULT now(), assigned_by text, merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass));
CREATE TABLE public.agents (first_name text NOT NULL, created_at timestamp without time zone DEFAULT now(), email text NOT NULL, territory text, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), user_id character varying NOT NULL, phone text NOT NULL, commission_rate numeric DEFAULT 5.00, last_name text NOT NULL, status text NOT NULL DEFAULT 'active'::text);
CREATE TABLE public.api_keys (contact_email text NOT NULL, key_secret text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), permissions jsonb NOT NULL DEFAULT '[]'::jsonb, is_active boolean DEFAULT true, name text NOT NULL, rate_limit integer DEFAULT 1000, organization_name text, last_used_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), key_id text NOT NULL, expires_at timestamp without time zone);
CREATE TABLE public.api_request_logs (ip_address text, error_message text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), response_size integer, method text NOT NULL, endpoint text NOT NULL, request_size integer, user_agent text, created_at timestamp without time zone NOT NULL DEFAULT now(), response_time integer, status_code integer NOT NULL, api_key_id integer);
CREATE TABLE public.audit_logs (ip_address text NOT NULL, action text NOT NULL, resource text, new_values jsonb, error_message text, session_id text, updated_at timestamp without time zone DEFAULT now(), user_email text, correlation_id character varying, data_classification text, resource_type text, risk_level text DEFAULT 'medium'::text, encryption_key_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), compliance_flags ARRAY, endpoint text, details jsonb, user_agent text, request_params jsonb, method text, user_id character varying, environment text DEFAULT 'development'::text, old_values jsonb, device_info jsonb, created_at timestamp without time zone DEFAULT now(), category text, status_code integer, timestamp timestamp without time zone NOT NULL DEFAULT now(), application_version text DEFAULT 'v1.0.0'::text, geolocation jsonb, notes text, request_id character varying, outcome text, metadata jsonb, resource_id text, retention_policy text, response_time integer, tags ARRAY, request_body jsonb, severity text DEFAULT 'info'::text);
CREATE TABLE public.business_ownership (created_at timestamp without time zone NOT NULL DEFAULT now(), owner_email text NOT NULL, signed_at timestamp without time zone, owner_name text NOT NULL, requires_signature boolean NOT NULL DEFAULT false, prospect_id integer, signature_type text, signature_image_path text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), form_submission_id integer, ownership_percentage numeric NOT NULL, digital_signature text, signature_token text);
CREATE TABLE public.campaign_assignments (campaign_id integer NOT NULL, assigned_by character varying, application_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, prospect_id integer, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass));
CREATE TABLE public.campaign_equipment (campaign_id integer NOT NULL, is_required boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), equipment_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_fee_values (value text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text, campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass));
CREATE TABLE public.campaigns (currency text NOT NULL DEFAULT 'USD'::text, acquirer text NOT NULL, is_default boolean NOT NULL DEFAULT false, pricing_type_id integer, created_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), description text, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), name text NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), equipment text);
CREATE TABLE public.data_access_logs (access_reason text, audit_log_id integer, data_volume integer, retention_period integer, created_at timestamp without time zone NOT NULL DEFAULT now(), field_accessed text, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), data_type text NOT NULL, table_name text NOT NULL, lawful_basis text, record_id text, access_type text NOT NULL, user_id character varying NOT NULL);
CREATE TABLE public.email_activity (template_id integer, template_name character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), status character varying NOT NULL, error_message text, clicked_at timestamp without time zone, sent_at timestamp without time zone DEFAULT now(), triggered_by character varying, trigger_source character varying, subject text NOT NULL, recipient_email character varying NOT NULL, opened_at timestamp without time zone, metadata jsonb, recipient_name character varying);
CREATE TABLE public.email_templates (category character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), is_active boolean DEFAULT true, variables jsonb, text_content text, subject text NOT NULL, name character varying NOT NULL, description text, html_content text NOT NULL);
CREATE TABLE public.email_triggers (id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), conditions jsonb, is_active boolean DEFAULT true, description text, created_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, name character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), template_id integer);
CREATE TABLE public.equipment_items (updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, description text, status text DEFAULT 'available'::text, manufacturer text, name text NOT NULL, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), model text, price numeric, category text);
CREATE TABLE public.fee_groups (category text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_by text, is_active boolean DEFAULT true, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, author text, name text NOT NULL, display_order integer DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), description text, fees jsonb DEFAULT '{}'::jsonb);
CREATE TABLE public.fee_item_groups (id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, name text NOT NULL, description text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fee_group_id integer NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, author text NOT NULL DEFAULT 'System'::text, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.fee_items (is_active boolean NOT NULL DEFAULT true, description text, author text NOT NULL DEFAULT 'System'::text, display_order integer NOT NULL DEFAULT 0, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, value_type text NOT NULL, fee_item_group_id integer, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), default_value text, name text NOT NULL, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fee_group_id integer NOT NULL, additional_info text);
CREATE TABLE public.locations (city text NOT NULL, name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, email text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, zip_code text NOT NULL, phone text, address text NOT NULL, state text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), latitude numeric, longitude numeric, status text DEFAULT 'active'::text, merchant_id integer);
CREATE TABLE public.login_attempts (email character varying, success boolean NOT NULL, username character varying, failure_reason character varying, created_at timestamp without time zone DEFAULT now(), ip_address character varying NOT NULL, user_agent text, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass));
CREATE TABLE public.merchant_prospects (notes text, agent_id integer NOT NULL, current_step integer DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), application_started_at timestamp without time zone, validated_at timestamp without time zone, last_name text NOT NULL, status text NOT NULL DEFAULT 'pending'::text, validation_token text, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), email text NOT NULL, first_name text NOT NULL, form_data text);
CREATE TABLE public.merchants (business_type text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, legal_name text, ein text, industry text, phone text, dba_name text, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), agent_id integer, user_id text, business_name text NOT NULL, website text, status text DEFAULT 'pending'::text);
CREATE TABLE public.pdf_form_fields (created_at timestamp without time zone DEFAULT now(), is_required boolean DEFAULT false, section text, position integer NOT NULL, field_type text NOT NULL, field_label text NOT NULL, form_id integer NOT NULL, field_name text NOT NULL, options ARRAY, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), default_value text, validation text);
CREATE TABLE public.pdf_form_submissions (data text NOT NULL, updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), is_public boolean DEFAULT false, submission_token text NOT NULL, created_at timestamp without time zone DEFAULT now(), submitted_by text, applicant_email text, status text DEFAULT 'draft'::text);
CREATE TABLE public.pdf_forms (allowed_roles ARRAY DEFAULT '{admin}'::text[], updated_at timestamp without time zone DEFAULT now(), name text NOT NULL, status text DEFAULT 'active'::text, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), description text, show_in_navigation boolean DEFAULT false, uploaded_by text NOT NULL, file_name text NOT NULL, navigation_title text, file_size integer NOT NULL);
CREATE TABLE public.pricing_type_fee_items (pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), is_required boolean NOT NULL DEFAULT true, fee_item_id integer NOT NULL);
CREATE TABLE public.pricing_types (description text, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), is_active boolean NOT NULL DEFAULT true, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, name text NOT NULL);
CREATE TABLE public.prospect_owners (signature_token text, prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email text NOT NULL, email_sent_at timestamp without time zone, updated_at timestamp without time zone DEFAULT now(), ownership_percentage numeric NOT NULL, name text NOT NULL, email_sent boolean DEFAULT false, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.prospect_signatures (signature_token text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), prospect_id integer NOT NULL, signature text NOT NULL, signature_type text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), owner_id integer NOT NULL);
CREATE TABLE public.schema_migrations (name character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), checksum character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, migration_id character varying NOT NULL, environment character varying NOT NULL);
CREATE TABLE public.security_events (detected_by text, detected_at timestamp without time zone NOT NULL DEFAULT now(), severity text NOT NULL, detection_method text, event_type text NOT NULL, resolved_by character varying, resolution text, investigation_notes text, affected_resources jsonb, assigned_to character varying, affected_users jsonb, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), alert_status text DEFAULT 'new'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), resolved_at timestamp without time zone, mitigation_actions jsonb, audit_log_id integer);
CREATE TABLE public.sessions (expire timestamp without time zone NOT NULL, sess json NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (amount numeric NOT NULL, status text DEFAULT 'pending'::text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), transaction_type text NOT NULL, location_id integer, processed_at timestamp with time zone, merchant_id integer);
CREATE TABLE public.two_factor_codes (expires_at timestamp without time zone NOT NULL, code character varying NOT NULL, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), type character varying NOT NULL, user_id character varying NOT NULL, used boolean DEFAULT false, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.user_dashboard_preferences (user_id text NOT NULL, position integer NOT NULL DEFAULT 0, is_visible boolean NOT NULL DEFAULT true, size text NOT NULL DEFAULT 'medium'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), widget_id text NOT NULL, id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), configuration jsonb DEFAULT '{}'::jsonb);
CREATE TABLE public.users (last_login_at timestamp without time zone, last_name character varying, password_reset_expires timestamp without time zone, password_reset_token character varying, status text NOT NULL DEFAULT 'active'::text, two_factor_enabled boolean DEFAULT false, permissions jsonb DEFAULT '{}'::jsonb, email character varying NOT NULL, id character varying NOT NULL, last_login_ip character varying, email_verification_token character varying, password_hash character varying NOT NULL, profile_image_url character varying, created_at timestamp without time zone DEFAULT now(), role text NOT NULL DEFAULT 'merchant'::text, first_name character varying, email_verified boolean DEFAULT false, updated_at timestamp without time zone DEFAULT now(), timezone character varying DEFAULT 'UTC'::character varying, username character varying NOT NULL, two_factor_secret character varying);