-- Database backup for production environment
-- Generated at: 2025-09-24T17:50:16.746Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (latitude real, postal_code text NOT NULL, city text NOT NULL, street2 text, location_id integer NOT NULL, street1 text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), state text NOT NULL, country text NOT NULL DEFAULT 'US'::text, geocoded_at timestamp without time zone, longitude real, timezone text, type text NOT NULL DEFAULT 'primary'::text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), geo_accuracy real);
CREATE TABLE public.agent_merchants (id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), merchant_id integer NOT NULL, agent_id integer NOT NULL, assigned_by text, assigned_at timestamp without time zone DEFAULT now());
CREATE TABLE public.agents (territory text, created_at timestamp without time zone DEFAULT now(), status text NOT NULL DEFAULT 'active'::text, last_name text NOT NULL, email text NOT NULL, user_id character varying NOT NULL, phone text NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), commission_rate numeric DEFAULT 5.00, first_name text NOT NULL);
CREATE TABLE public.api_keys (contact_email text NOT NULL, last_used_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), key_id text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, is_active boolean DEFAULT true, name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), expires_at timestamp without time zone, rate_limit integer DEFAULT 1000, key_secret text NOT NULL, organization_name text, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.api_request_logs (error_message text, response_size integer, created_at timestamp without time zone NOT NULL DEFAULT now(), api_key_id integer, status_code integer NOT NULL, ip_address text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), method text NOT NULL, user_agent text, endpoint text NOT NULL, response_time integer, request_size integer);
CREATE TABLE public.audit_logs (resource text, action text NOT NULL, new_values jsonb, error_message text, session_id text, ip_address text NOT NULL, correlation_id character varying, data_classification text, resource_type text, risk_level text DEFAULT 'medium'::text, encryption_key_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), endpoint text, details jsonb, user_agent text, request_params jsonb, method text, environment text DEFAULT 'development'::text, device_info jsonb, created_at timestamp without time zone DEFAULT now(), status_code integer, application_version text DEFAULT 'v1.0.0'::text, notes text, request_id character varying, outcome text, resource_id text, retention_policy text, tags ARRAY, severity text DEFAULT 'info'::text, request_body jsonb, response_time integer, metadata jsonb, geolocation jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), category text, old_values jsonb, user_id character varying, compliance_flags ARRAY, user_email text, updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.business_ownership (owner_email text NOT NULL, prospect_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), ownership_percentage numeric NOT NULL, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), signature_image_path text, digital_signature text, signature_token text, form_submission_id integer, signature_type text, signed_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), requires_signature boolean NOT NULL DEFAULT false, owner_name text NOT NULL);
CREATE TABLE public.campaign_assignments (assigned_by character varying, assigned_at timestamp without time zone NOT NULL DEFAULT now(), application_id integer, campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), prospect_id integer, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.campaign_equipment (is_required boolean NOT NULL DEFAULT false, equipment_item_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0);
CREATE TABLE public.campaign_fee_values (campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), value text NOT NULL, fee_group_fee_item_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaigns (acquirer text NOT NULL, equipment text, currency text NOT NULL DEFAULT 'USD'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by character varying, pricing_type_id integer, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), is_default boolean NOT NULL DEFAULT false, description text);
CREATE TABLE public.data_access_logs (field_accessed text, record_id text, retention_period integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), user_id character varying NOT NULL, data_type text NOT NULL, access_type text NOT NULL, table_name text NOT NULL, access_reason text, created_at timestamp without time zone NOT NULL DEFAULT now(), data_volume integer, lawful_basis text, audit_log_id integer);
CREATE TABLE public.email_activity (status character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), metadata jsonb, error_message text, clicked_at timestamp without time zone, recipient_name character varying, template_name character varying NOT NULL, opened_at timestamp without time zone, trigger_source character varying, template_id integer, subject text NOT NULL, sent_at timestamp without time zone DEFAULT now(), recipient_email character varying NOT NULL, triggered_by character varying);
CREATE TABLE public.email_templates (name character varying NOT NULL, html_content text NOT NULL, subject text NOT NULL, is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), category character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), description text, created_at timestamp without time zone DEFAULT now(), variables jsonb, text_content text);
CREATE TABLE public.email_triggers (is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), template_id integer, description text, name character varying NOT NULL, trigger_event character varying NOT NULL, conditions jsonb, updated_at timestamp without time zone DEFAULT now(), created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.equipment_items (image_data text, status text DEFAULT 'available'::text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), manufacturer text, image_url text, is_active boolean NOT NULL DEFAULT true, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, price numeric, name text NOT NULL, model_number text, category text, specifications jsonb DEFAULT '{}'::jsonb, model text, description text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.fee_group_fee_items (fee_group_id integer NOT NULL, fee_item_group_id integer, is_required boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, fee_item_id integer NOT NULL);
CREATE TABLE public.fee_groups (display_order integer DEFAULT 0, fees jsonb DEFAULT '{}'::jsonb, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, is_active boolean DEFAULT true, author text, created_by text, description text, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, name text NOT NULL, category text);
CREATE TABLE public.fee_item_groups (description text, fee_group_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, author text NOT NULL DEFAULT 'System'::text, name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass));
CREATE TABLE public.fee_items (description text, author text NOT NULL DEFAULT 'System'::text, value_type text NOT NULL, name text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, fee_item_group_id integer, is_active boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, default_value text, additional_info text);
CREATE TABLE public.locations (operating_hours jsonb, name text NOT NULL, zip_code text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), email text, type text NOT NULL DEFAULT 'store'::text, city text NOT NULL, longitude numeric, mid character varying, status text DEFAULT 'active'::text, latitude numeric, address text NOT NULL, state text NOT NULL, phone text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, merchant_id integer);
CREATE TABLE public.login_attempts (failure_reason character varying, username character varying, created_at timestamp without time zone DEFAULT now(), email character varying, success boolean NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), user_agent text, ip_address character varying NOT NULL);
CREATE TABLE public.merchant_prospects (application_started_at timestamp without time zone, last_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), email text NOT NULL, validated_at timestamp without time zone, agent_id integer NOT NULL, first_name text NOT NULL, notes text, current_step integer DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), validation_token text, form_data text, status text NOT NULL DEFAULT 'pending'::text, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass));
CREATE TABLE public.merchants (website text, phone text, industry text, processing_fee numeric NOT NULL DEFAULT 2.50, business_type text, agent_id integer, dba_name text, email text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), ein text, status text DEFAULT 'pending'::text, user_id text, business_name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, legal_name text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.pdf_form_fields (validation text, position integer NOT NULL, created_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, section text, default_value text, options ARRAY, field_name text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), field_type text NOT NULL, is_required boolean DEFAULT false, field_label text NOT NULL);
CREATE TABLE public.pdf_form_submissions (submitted_by text, submission_token text NOT NULL, data text NOT NULL, applicant_email text, status text DEFAULT 'draft'::text, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), is_public boolean DEFAULT false, form_id integer NOT NULL);
CREATE TABLE public.pdf_forms (allowed_roles ARRAY DEFAULT '{admin}'::text[], updated_at timestamp without time zone DEFAULT now(), status text DEFAULT 'active'::text, file_name text NOT NULL, navigation_title text, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), name text NOT NULL, description text, show_in_navigation boolean DEFAULT false, uploaded_by text NOT NULL, file_size integer NOT NULL);
CREATE TABLE public.pricing_type_fee_items (created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), is_required boolean NOT NULL DEFAULT true);
CREATE TABLE public.pricing_types (name text NOT NULL, is_active boolean NOT NULL DEFAULT true, author text NOT NULL DEFAULT 'System'::text, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, description text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass));
CREATE TABLE public.prospect_owners (email_sent boolean DEFAULT false, name text NOT NULL, prospect_id integer NOT NULL, signature_token text, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), email_sent_at timestamp without time zone, ownership_percentage numeric NOT NULL, created_at timestamp without time zone DEFAULT now(), email text NOT NULL);
CREATE TABLE public.prospect_signatures (signature_token text NOT NULL, owner_id integer NOT NULL, prospect_id integer NOT NULL, signature_type text NOT NULL, signature text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), submitted_at timestamp without time zone DEFAULT now());
CREATE TABLE public.schema_migrations (checksum character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), name character varying NOT NULL, environment character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, migration_id character varying NOT NULL);
CREATE TABLE public.security_events (mitigation_actions jsonb, detected_by text, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), severity text NOT NULL, affected_users jsonb, detection_method text, event_type text NOT NULL, detected_at timestamp without time zone NOT NULL DEFAULT now(), assigned_to character varying, resolved_by character varying, created_at timestamp without time zone NOT NULL DEFAULT now(), resolution text, alert_status text DEFAULT 'new'::text, audit_log_id integer, resolved_at timestamp without time zone, investigation_notes text, updated_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb);
CREATE TABLE public.sessions (expire timestamp without time zone NOT NULL, sess json NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, payment_method text, location_id integer, created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, net_amount numeric DEFAULT 0, processed_at timestamp with time zone, mid character varying, transaction_type text NOT NULL, transaction_id text NOT NULL DEFAULT ''::text, processing_fee numeric DEFAULT 0, merchant_id integer, commission_amount numeric DEFAULT 0, amount numeric NOT NULL, status text DEFAULT 'pending'::text, reference_number text, commission_rate numeric DEFAULT 0.025, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass));
CREATE TABLE public.two_factor_codes (created_at timestamp without time zone DEFAULT now(), user_id character varying NOT NULL, used boolean DEFAULT false, type character varying NOT NULL, expires_at timestamp without time zone NOT NULL, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), code character varying NOT NULL);
CREATE TABLE public.user_dashboard_preferences (is_visible boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), configuration jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), position integer NOT NULL DEFAULT 0, widget_id text NOT NULL, size text NOT NULL DEFAULT 'medium'::text, id integer NOT NULL, user_id text NOT NULL);
CREATE TABLE public.users (profile_image_url character varying, first_name character varying, email_verified boolean DEFAULT false, password_reset_expires timestamp without time zone, last_name character varying, two_factor_enabled boolean DEFAULT false, id character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), status text NOT NULL DEFAULT 'active'::text, email_verification_token character varying, phone character varying NOT NULL DEFAULT ''::character varying, password_hash character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), timezone character varying DEFAULT 'UTC'::character varying, last_login_at timestamp without time zone, two_factor_secret character varying, communication_preference text NOT NULL DEFAULT 'email'::text, last_login_ip character varying, email character varying NOT NULL, username character varying NOT NULL, roles ARRAY DEFAULT '{merchant}'::text[], permissions jsonb DEFAULT '{}'::jsonb, password_reset_token character varying);