-- Database backup for test environment
-- Generated at: 2025-09-26T03:50:55.080Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (latitude real, location_id integer NOT NULL, geo_accuracy real, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), country text NOT NULL DEFAULT 'US'::text, street1 text NOT NULL, postal_code text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), geocoded_at timestamp without time zone, street2 text, state text NOT NULL, city text NOT NULL, type text NOT NULL DEFAULT 'primary'::text, timezone text, longitude real);
CREATE TABLE public.agent_merchants (agent_id integer NOT NULL, merchant_id integer NOT NULL, assigned_by text, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), assigned_at timestamp without time zone DEFAULT now());
CREATE TABLE public.agents (status text NOT NULL DEFAULT 'active'::text, commission_rate numeric DEFAULT 5.00, email text NOT NULL, created_at timestamp without time zone DEFAULT now(), company_id integer, user_id character varying NOT NULL, territory text, first_name text NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), last_name text NOT NULL, phone text NOT NULL);
CREATE TABLE public.api_keys (expires_at timestamp without time zone, name text NOT NULL, key_secret text NOT NULL, rate_limit integer DEFAULT 1000, contact_email text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, organization_name text, last_used_at timestamp without time zone, key_id text NOT NULL, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), is_active boolean DEFAULT true, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.api_request_logs (created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), method text NOT NULL, request_size integer, status_code integer NOT NULL, ip_address text, user_agent text, error_message text, api_key_id integer, response_size integer, endpoint text NOT NULL, response_time integer);
CREATE TABLE public.audit_logs (updated_at timestamp without time zone DEFAULT now(), old_values jsonb, retention_policy text, created_at timestamp without time zone NOT NULL DEFAULT now(), environment text DEFAULT 'production'::text, application_version text, resource_type text, user_email text, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), tags jsonb, request_body jsonb, ip_address text NOT NULL, severity text DEFAULT 'info'::text, user_agent text, data_classification text, correlation_id character varying, action text NOT NULL, new_values jsonb, category text, details jsonb, encryption_key_id character varying, device_info jsonb, request_params jsonb, geolocation jsonb, compliance_flags jsonb, endpoint text, response_time integer, method text, resource_id text, request_id character varying, outcome text, risk_level text NOT NULL DEFAULT 'low'::text, timestamp timestamp without time zone NOT NULL DEFAULT now(), session_id text, metadata jsonb, notes text, user_id character varying, resource text NOT NULL, error_message text, status_code integer);
CREATE TABLE public.business_ownership (updated_at timestamp without time zone NOT NULL DEFAULT now(), signature_image_path text, created_at timestamp without time zone NOT NULL DEFAULT now(), owner_email text NOT NULL, digital_signature text, prospect_id integer, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), requires_signature boolean NOT NULL DEFAULT false, owner_name text NOT NULL, signed_at timestamp without time zone, signature_type text, signature_token text, form_submission_id integer, ownership_percentage numeric NOT NULL);
CREATE TABLE public.campaign_assignments (prospect_id integer, is_active boolean NOT NULL DEFAULT true, campaign_id integer NOT NULL, application_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), assigned_by character varying, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass));
CREATE TABLE public.campaign_equipment (is_required boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, equipment_item_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL);
CREATE TABLE public.campaign_fee_values (id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), fee_item_id integer, fee_group_fee_item_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), value_type text NOT NULL DEFAULT 'percentage'::text, campaign_id integer NOT NULL, value text NOT NULL);
CREATE TABLE public.campaigns (currency text NOT NULL DEFAULT 'USD'::text, description text, equipment text, created_by character varying, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), is_default boolean NOT NULL DEFAULT false, acquirer text NOT NULL, pricing_type_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.companies (name text NOT NULL, description text, status text NOT NULL DEFAULT 'active'::text, business_type text, id integer NOT NULL DEFAULT nextval('companies_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, phone text, industry text, tax_id character varying, address jsonb, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, email text, logo_url text, website text);
CREATE TABLE public.data_access_logs (table_name text NOT NULL, access_type text NOT NULL, audit_log_id integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), field_accessed text, retention_period integer, user_id character varying NOT NULL, data_volume integer, lawful_basis text, record_id text, data_type text NOT NULL, access_reason text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.email_activity (clicked_at timestamp without time zone, triggered_by character varying, sent_at timestamp without time zone DEFAULT now(), template_id integer, metadata jsonb, status character varying NOT NULL, opened_at timestamp without time zone, error_message text, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), recipient_name character varying, subject text NOT NULL, trigger_source character varying, recipient_email character varying NOT NULL, template_name character varying NOT NULL);
CREATE TABLE public.email_templates (subject text NOT NULL, variables jsonb, text_content text, html_content text NOT NULL, name character varying NOT NULL, category character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), description text, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), is_active boolean DEFAULT true);
CREATE TABLE public.email_triggers (conditions jsonb, is_active boolean DEFAULT true, trigger_event character varying NOT NULL, name character varying NOT NULL, template_id integer, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), description text, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.equipment_items (manufacturer text, category text, model text, model_number text, description text, updated_at timestamp without time zone NOT NULL DEFAULT now(), specifications jsonb DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true, price numeric, image_data text, created_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), status text DEFAULT 'available'::text, image_url text);
CREATE TABLE public.fee_group_fee_items (id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, fee_group_id integer NOT NULL, is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone DEFAULT now(), fee_item_id integer NOT NULL, fee_item_group_id integer);
CREATE TABLE public.fee_groups (description text, category text, created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, fees jsonb DEFAULT '{}'::jsonb, author text NOT NULL DEFAULT 'System'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by text, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), name text NOT NULL, is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.fee_item_groups (fee_group_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, description text);
CREATE TABLE public.fee_items (display_order integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, additional_info text, value_type text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), fee_item_group_id integer, name text NOT NULL, description text, default_value text, author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.locations (status text NOT NULL DEFAULT 'active'::text, city text NOT NULL, state text NOT NULL, phone text, email text, created_at timestamp without time zone NOT NULL DEFAULT now(), operating_hours jsonb, merchant_id integer NOT NULL, latitude numeric, mid character varying, zip_code text NOT NULL, longitude numeric, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), name text NOT NULL, address text NOT NULL, type text NOT NULL DEFAULT 'store'::text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.login_attempts (failure_reason character varying, created_at timestamp without time zone DEFAULT now(), email character varying, username character varying, success boolean NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), user_agent text, ip_address character varying NOT NULL);
CREATE TABLE public.merchant_prospects (created_at timestamp without time zone NOT NULL DEFAULT now(), validated_at timestamp without time zone, current_step integer DEFAULT 0, last_name text NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), form_data text, notes text, status text NOT NULL DEFAULT 'pending'::text, email text NOT NULL, validation_token text, first_name text NOT NULL, application_started_at timestamp without time zone, agent_id integer NOT NULL);
CREATE TABLE public.merchants (website text, business_type text NOT NULL, agent_id integer, legal_name text, phone text NOT NULL, company_id integer, processing_fee numeric NOT NULL DEFAULT 2.50, status text NOT NULL DEFAULT 'active'::text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), user_id character varying, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, industry text, email text NOT NULL, business_name text NOT NULL, dba_name text, created_at timestamp without time zone NOT NULL DEFAULT now(), ein text);
CREATE TABLE public.pdf_form_fields (validation text, field_label text NOT NULL, field_name text NOT NULL, is_required boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), default_value text, field_type text NOT NULL, section text, form_id integer NOT NULL, position integer NOT NULL, created_at timestamp without time zone DEFAULT now(), options ARRAY);
CREATE TABLE public.pdf_form_submissions (created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, applicant_email text, data text NOT NULL, is_public boolean DEFAULT false, status text DEFAULT 'draft'::text, submitted_by text, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), submission_token text NOT NULL);
CREATE TABLE public.pdf_forms (id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), show_in_navigation boolean DEFAULT false, name text NOT NULL, file_size integer NOT NULL, uploaded_by text NOT NULL, status text DEFAULT 'active'::text, description text, file_name text NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], navigation_title text, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.pricing_type_fee_items (id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT true, pricing_type_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL);
CREATE TABLE public.pricing_types (description text, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.prospect_owners (signature_token text, ownership_percentage numeric NOT NULL, updated_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), prospect_id integer NOT NULL, email_sent boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), email_sent_at timestamp without time zone, name text NOT NULL, email text NOT NULL);
CREATE TABLE public.prospect_signatures (prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), signature_token text NOT NULL, signature text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), owner_id integer NOT NULL, signature_type text NOT NULL);
CREATE TABLE public.schema_migrations (name character varying NOT NULL, environment character varying NOT NULL, checksum character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), migration_id character varying NOT NULL);
CREATE TABLE public.security_events (detected_by text, detection_method text, severity text NOT NULL, affected_users jsonb, assigned_to character varying, audit_log_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), alert_status text DEFAULT 'new'::text, resolution text, detected_at timestamp without time zone NOT NULL DEFAULT now(), resolved_by character varying, affected_resources jsonb, mitigation_actions jsonb, investigation_notes text, event_type text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), resolved_at timestamp without time zone);
CREATE TABLE public.sessions (sess jsonb NOT NULL, expire timestamp without time zone NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (transaction_type text NOT NULL, processed_at timestamp with time zone, net_amount numeric DEFAULT 0, processing_fee numeric DEFAULT 0, transaction_id text NOT NULL DEFAULT ''::text, created_at timestamp without time zone DEFAULT now(), amount numeric NOT NULL, reference_number text, commission_rate numeric DEFAULT 0.025, merchant_id integer NOT NULL, commission_amount numeric DEFAULT 0, status text NOT NULL, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), mid character varying, payment_method text, location_id integer);
CREATE TABLE public.two_factor_codes (used boolean DEFAULT false, code character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), type character varying NOT NULL, expires_at timestamp without time zone NOT NULL, user_id character varying NOT NULL);
CREATE TABLE public.user_dashboard_preferences (user_id text NOT NULL, id integer NOT NULL, position integer NOT NULL DEFAULT 0, created_at timestamp without time zone NOT NULL DEFAULT now(), size text NOT NULL DEFAULT 'medium'::text, configuration jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_visible boolean NOT NULL DEFAULT true, widget_id text NOT NULL);
CREATE TABLE public.users (email_verified boolean DEFAULT false, email_verification_token character varying, permissions jsonb DEFAULT '{}'::jsonb, password_reset_token character varying, roles ARRAY DEFAULT '{merchant}'::text[], profile_image_url character varying, two_factor_enabled boolean DEFAULT false, username character varying NOT NULL, status text NOT NULL DEFAULT 'active'::text, password_reset_expires timestamp without time zone, last_login_at timestamp without time zone, id character varying NOT NULL, phone text NOT NULL DEFAULT ''::character varying, email character varying NOT NULL, last_name character varying, password_hash character varying NOT NULL, two_factor_secret character varying, communication_preference text NOT NULL DEFAULT 'email'::text, first_name character varying, created_at timestamp without time zone DEFAULT now(), updated_at timestamp without time zone DEFAULT now(), timezone character varying DEFAULT 'UTC'::character varying, last_login_ip character varying);