-- Database backup for test environment
-- Generated at: 2025-09-24T17:47:26.031Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (city text NOT NULL, location_id integer NOT NULL, latitude real, postal_code text NOT NULL, longitude real, type text NOT NULL DEFAULT 'primary'::text, state text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), geocoded_at timestamp without time zone, timezone text, street2 text, geo_accuracy real, street1 text NOT NULL, country text NOT NULL DEFAULT 'US'::text);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), assigned_by text, agent_id integer NOT NULL, merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass));
CREATE TABLE public.agents (id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), first_name text NOT NULL, status text NOT NULL DEFAULT 'active'::text, email text NOT NULL, phone text NOT NULL, user_id character varying NOT NULL, last_name text NOT NULL, territory text, created_at timestamp without time zone DEFAULT now(), commission_rate numeric DEFAULT 5.00);
CREATE TABLE public.api_keys (key_secret text NOT NULL, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), organization_name text, created_at timestamp without time zone NOT NULL DEFAULT now(), last_used_at timestamp without time zone, contact_email text NOT NULL, key_id text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, name text NOT NULL, is_active boolean DEFAULT true, expires_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), rate_limit integer DEFAULT 1000);
CREATE TABLE public.api_request_logs (error_message text, response_time integer, created_at timestamp without time zone NOT NULL DEFAULT now(), method text NOT NULL, user_agent text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), request_size integer, response_size integer, status_code integer NOT NULL, api_key_id integer, endpoint text NOT NULL, ip_address text);
CREATE TABLE public.audit_logs (timestamp timestamp without time zone NOT NULL DEFAULT now(), endpoint text, encryption_key_id character varying, request_id character varying, new_values jsonb, outcome text, risk_level text NOT NULL DEFAULT 'low'::text, correlation_id character varying, request_params jsonb, method text, application_version text, user_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), data_classification text, resource_type text, created_at timestamp without time zone NOT NULL DEFAULT now(), tags jsonb, details jsonb, geolocation jsonb, session_id text, device_info jsonb, compliance_flags jsonb, error_message text, old_values jsonb, notes text, retention_policy text, action text NOT NULL, response_time integer, updated_at timestamp without time zone DEFAULT now(), resource_id text, request_body jsonb, ip_address text NOT NULL, metadata jsonb, status_code integer, environment text DEFAULT 'production'::text, user_email text, user_agent text, severity text DEFAULT 'info'::text, resource text NOT NULL, category text);
CREATE TABLE public.business_ownership (signature_image_path text, created_at timestamp without time zone NOT NULL DEFAULT now(), prospect_id integer, updated_at timestamp without time zone NOT NULL DEFAULT now(), form_submission_id integer, requires_signature boolean NOT NULL DEFAULT false, signed_at timestamp without time zone, digital_signature text, signature_type text, ownership_percentage numeric NOT NULL, signature_token text, owner_name text NOT NULL, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), owner_email text NOT NULL);
CREATE TABLE public.campaign_assignments (is_active boolean NOT NULL DEFAULT true, application_id integer, prospect_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), assigned_by character varying);
CREATE TABLE public.campaign_equipment (equipment_item_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass));
CREATE TABLE public.campaign_fee_values (id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), value_type text NOT NULL DEFAULT 'percentage'::text, campaign_id integer NOT NULL, value text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_fee_item_id integer, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaigns (acquirer text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), is_default boolean NOT NULL DEFAULT false, description text, pricing_type_id integer, equipment text, name text NOT NULL, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), currency text NOT NULL DEFAULT 'USD'::text, created_by character varying);
CREATE TABLE public.data_access_logs (access_type text NOT NULL, field_accessed text, access_reason text, created_at timestamp without time zone NOT NULL DEFAULT now(), retention_period integer, table_name text NOT NULL, user_id character varying NOT NULL, audit_log_id integer, record_id text, data_volume integer, lawful_basis text, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), data_type text NOT NULL);
CREATE TABLE public.email_activity (recipient_email character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), template_id integer, sent_at timestamp without time zone DEFAULT now(), triggered_by character varying, template_name character varying NOT NULL, opened_at timestamp without time zone, error_message text, clicked_at timestamp without time zone, recipient_name character varying, status character varying NOT NULL, subject text NOT NULL, metadata jsonb, trigger_source character varying);
CREATE TABLE public.email_templates (category character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), subject text NOT NULL, description text, text_content text, created_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, is_active boolean DEFAULT true, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), variables jsonb, html_content text NOT NULL);
CREATE TABLE public.email_triggers (is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT now(), conditions jsonb, trigger_event character varying NOT NULL, updated_at timestamp without time zone DEFAULT now(), description text, name character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), template_id integer);
CREATE TABLE public.equipment_items (category text, image_data text, specifications jsonb DEFAULT '{}'::jsonb, is_active boolean NOT NULL DEFAULT true, description text, price numeric, model text, manufacturer text, image_url text, name text NOT NULL, model_number text, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), status text DEFAULT 'available'::text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass));
CREATE TABLE public.fee_group_fee_items (fee_item_group_id integer, created_at timestamp without time zone DEFAULT now(), is_required boolean NOT NULL DEFAULT false, fee_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, fee_group_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass));
CREATE TABLE public.fee_groups (display_order integer NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, category text, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by text, author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), fees jsonb DEFAULT '{}'::jsonb, description text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_item_groups (author text NOT NULL DEFAULT 'System'::text, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, fee_group_id integer NOT NULL, description text);
CREATE TABLE public.fee_items (value_type text NOT NULL, author text NOT NULL DEFAULT 'System'::text, display_order integer NOT NULL DEFAULT 0, default_value text, fee_item_group_id integer, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, additional_info text, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), description text);
CREATE TABLE public.locations (email text, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, city text NOT NULL, zip_code text NOT NULL, state text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), mid character varying, longitude numeric, latitude numeric, merchant_id integer NOT NULL, name text NOT NULL, status text NOT NULL DEFAULT 'active'::text, address text NOT NULL, type text NOT NULL DEFAULT 'store'::text, phone text, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), operating_hours jsonb);
CREATE TABLE public.login_attempts (username character varying, user_agent text, success boolean NOT NULL, failure_reason character varying, ip_address character varying NOT NULL, email character varying, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass));
CREATE TABLE public.merchant_prospects (id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), email text NOT NULL, first_name text NOT NULL, current_step integer DEFAULT 0, validated_at timestamp without time zone, validation_token text, application_started_at timestamp without time zone, last_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'pending'::text, form_data text, notes text, agent_id integer NOT NULL);
CREATE TABLE public.merchants (user_id character varying, business_name text NOT NULL, processing_fee numeric NOT NULL DEFAULT 2.50, business_type text NOT NULL, dba_name text, legal_name text, ein text, email text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), phone text NOT NULL, industry text, created_at timestamp without time zone NOT NULL DEFAULT now(), website text, agent_id integer, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, status text NOT NULL DEFAULT 'active'::text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric);
CREATE TABLE public.pdf_form_fields (field_name text NOT NULL, position integer NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), options ARRAY, form_id integer NOT NULL, validation text, field_label text NOT NULL, section text, default_value text, is_required boolean DEFAULT false, field_type text NOT NULL);
CREATE TABLE public.pdf_form_submissions (updated_at timestamp without time zone DEFAULT now(), submitted_by text, submission_token text NOT NULL, created_at timestamp without time zone DEFAULT now(), data text NOT NULL, form_id integer NOT NULL, applicant_email text, is_public boolean DEFAULT false, status text DEFAULT 'draft'::text, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass));
CREATE TABLE public.pdf_forms (id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), file_size integer NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], name text NOT NULL, updated_at timestamp without time zone DEFAULT now(), show_in_navigation boolean DEFAULT false, description text, created_at timestamp without time zone DEFAULT now(), uploaded_by text NOT NULL, status text DEFAULT 'active'::text, navigation_title text, file_name text NOT NULL);
CREATE TABLE public.pricing_type_fee_items (id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), pricing_type_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, is_required boolean NOT NULL DEFAULT true, fee_item_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.pricing_types (name text NOT NULL, author text NOT NULL DEFAULT 'System'::text, description text, is_active boolean NOT NULL DEFAULT true, updated_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.prospect_owners (ownership_percentage numeric NOT NULL, email_sent_at timestamp without time zone, created_at timestamp without time zone DEFAULT now(), name text NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), email text NOT NULL, email_sent boolean DEFAULT false, prospect_id integer NOT NULL, signature_token text, updated_at timestamp without time zone DEFAULT now());
CREATE TABLE public.prospect_signatures (signature_type text NOT NULL, signature text NOT NULL, prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), owner_id integer NOT NULL, submitted_at timestamp without time zone DEFAULT now(), signature_token text NOT NULL);
CREATE TABLE public.schema_migrations (checksum character varying NOT NULL, environment character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, name character varying NOT NULL, migration_id character varying NOT NULL);
CREATE TABLE public.security_events (resolved_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), affected_resources jsonb, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), resolution text, resolved_at timestamp without time zone, investigation_notes text, detected_at timestamp without time zone NOT NULL DEFAULT now(), affected_users jsonb, created_at timestamp without time zone NOT NULL DEFAULT now(), detected_by text, assigned_to character varying, audit_log_id integer, severity text NOT NULL, detection_method text, alert_status text DEFAULT 'new'::text, mitigation_actions jsonb, event_type text NOT NULL);
CREATE TABLE public.sessions (sess jsonb NOT NULL, sid character varying NOT NULL, expire timestamp without time zone NOT NULL);
CREATE TABLE public.transactions (amount numeric NOT NULL, created_at timestamp without time zone DEFAULT now(), transaction_id text NOT NULL DEFAULT ''::text, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), transaction_type text NOT NULL, payment_method text, processed_at timestamp with time zone, status text NOT NULL, net_amount numeric DEFAULT 0, processing_fee numeric DEFAULT 0, merchant_id integer NOT NULL, commission_amount numeric DEFAULT 0, location_id integer, commission_rate numeric DEFAULT 0.025, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, mid character varying, reference_number text);
CREATE TABLE public.two_factor_codes (id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), type character varying NOT NULL, code character varying NOT NULL, used boolean DEFAULT false, user_id character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), expires_at timestamp without time zone NOT NULL);
CREATE TABLE public.user_dashboard_preferences (user_id text NOT NULL, is_visible boolean NOT NULL DEFAULT true, created_at timestamp without time zone NOT NULL DEFAULT now(), position integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), widget_id text NOT NULL, configuration jsonb DEFAULT '{}'::jsonb, size text NOT NULL DEFAULT 'medium'::text, id integer NOT NULL);
CREATE TABLE public.users (username character varying NOT NULL, email_verification_token character varying, roles ARRAY DEFAULT '{merchant}'::text[], communication_preference text NOT NULL DEFAULT 'email'::text, password_reset_expires timestamp without time zone, timezone character varying DEFAULT 'UTC'::character varying, status text NOT NULL DEFAULT 'active'::text, profile_image_url character varying, last_login_at timestamp without time zone, updated_at timestamp without time zone DEFAULT now(), permissions jsonb DEFAULT '{}'::jsonb, two_factor_enabled boolean DEFAULT false, email character varying NOT NULL, password_hash character varying NOT NULL, last_login_ip character varying, first_name character varying, id character varying NOT NULL, last_name character varying, email_verified boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), password_reset_token character varying, phone character varying NOT NULL DEFAULT ''::character varying, two_factor_secret character varying);