-- Database backup for test environment
-- Generated at: 2025-08-18T18:00:02.905Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (street2 text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), latitude real, type text NOT NULL DEFAULT 'primary'::text, street1 text NOT NULL, longitude real, timezone text, created_at timestamp without time zone NOT NULL DEFAULT now(), geo_accuracy real, location_id integer NOT NULL, city text NOT NULL, geocoded_at timestamp without time zone, state text NOT NULL, postal_code text NOT NULL, country text NOT NULL DEFAULT 'US'::text);
CREATE TABLE public.agent_merchants (id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), merchant_id integer NOT NULL, assigned_by text, agent_id integer NOT NULL, assigned_at timestamp without time zone DEFAULT now());
CREATE TABLE public.agents (commission_rate numeric DEFAULT 5.00, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), phone text NOT NULL, last_name text NOT NULL, created_at timestamp without time zone DEFAULT now(), user_id character varying NOT NULL, first_name text NOT NULL, status text NOT NULL DEFAULT 'active'::text, email text NOT NULL, territory text);
CREATE TABLE public.api_keys (key_id text NOT NULL, expires_at timestamp without time zone, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), last_used_at timestamp without time zone, contact_email text NOT NULL, name text NOT NULL, is_active boolean DEFAULT true, permissions jsonb NOT NULL DEFAULT '[]'::jsonb, rate_limit integer DEFAULT 1000, organization_name text, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), key_secret text NOT NULL);
CREATE TABLE public.api_request_logs (response_size integer, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), error_message text, endpoint text NOT NULL, user_agent text, request_size integer, method text NOT NULL, ip_address text, response_time integer, created_at timestamp without time zone NOT NULL DEFAULT now(), status_code integer NOT NULL, api_key_id integer);
CREATE TABLE public.audit_logs (resource text NOT NULL, ip_address text NOT NULL, user_id character varying, user_email text, data_classification text, error_message text, old_values jsonb, resource_type text, environment text DEFAULT 'production'::text, geolocation jsonb, created_at timestamp without time zone NOT NULL DEFAULT now(), tags jsonb, notes text, action text NOT NULL, updated_at timestamp without time zone DEFAULT now(), retention_policy text, method text, request_params jsonb, correlation_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), compliance_flags jsonb, details jsonb, resource_id text, encryption_key_id character varying, category text, risk_level text NOT NULL DEFAULT 'low'::text, outcome text, response_time integer, metadata jsonb, new_values jsonb, request_id character varying, request_body jsonb, endpoint text, status_code integer, timestamp timestamp without time zone NOT NULL DEFAULT now(), device_info jsonb, session_id text, application_version text, user_agent text, severity text DEFAULT 'info'::text);
CREATE TABLE public.business_ownership (updated_at timestamp without time zone NOT NULL DEFAULT now(), digital_signature text, signed_at timestamp without time zone, prospect_id integer, signature_token text, signature_type text, requires_signature boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), form_submission_id integer, owner_name text NOT NULL, ownership_percentage numeric NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), owner_email text NOT NULL, signature_image_path text);
CREATE TABLE public.campaign_assignments (assigned_at timestamp without time zone NOT NULL DEFAULT now(), application_id integer, campaign_id integer NOT NULL, is_active boolean NOT NULL DEFAULT true, assigned_by character varying, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), prospect_id integer);
CREATE TABLE public.campaign_equipment (is_required boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, equipment_item_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass));
CREATE TABLE public.campaign_fee_values (fee_item_id integer NOT NULL, value text NOT NULL, campaign_id integer NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass));
CREATE TABLE public.campaigns (created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL, created_by character varying, updated_at timestamp without time zone NOT NULL DEFAULT now(), pricing_type_id integer, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), equipment text, acquirer text NOT NULL, is_default boolean NOT NULL DEFAULT false, description text, currency text NOT NULL DEFAULT 'USD'::text);
CREATE TABLE public.data_access_logs (retention_period integer, access_type text NOT NULL, access_reason text, user_id character varying NOT NULL, table_name text NOT NULL, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), data_type text NOT NULL, lawful_basis text, record_id text, field_accessed text, data_volume integer, audit_log_id integer);
CREATE TABLE public.email_activity (clicked_at timestamp without time zone, template_name character varying NOT NULL, metadata jsonb, subject text NOT NULL, recipient_email character varying NOT NULL, opened_at timestamp without time zone, triggered_by character varying, trigger_source character varying, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), sent_at timestamp without time zone DEFAULT now(), status character varying NOT NULL, error_message text, template_id integer, recipient_name character varying);
CREATE TABLE public.email_templates (description text, created_at timestamp without time zone DEFAULT now(), is_active boolean DEFAULT true, name character varying NOT NULL, text_content text, variables jsonb, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), updated_at timestamp without time zone DEFAULT now(), subject text NOT NULL, html_content text NOT NULL, category character varying NOT NULL);
CREATE TABLE public.email_triggers (updated_at timestamp without time zone DEFAULT now(), conditions jsonb, template_id integer, description text, is_active boolean DEFAULT true, trigger_event character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), name character varying NOT NULL, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.equipment_items (category text, status text DEFAULT 'available'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), model_number text, manufacturer text, model text, is_active boolean NOT NULL DEFAULT true, image_url text, image_data text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), specifications jsonb DEFAULT '{}'::jsonb, description text, created_at timestamp without time zone NOT NULL DEFAULT now(), price numeric, name text NOT NULL);
CREATE TABLE public.fee_groups (updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by text, name text NOT NULL, category text, is_active boolean NOT NULL DEFAULT true, author text NOT NULL DEFAULT 'System'::text, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), description text, created_at timestamp without time zone NOT NULL DEFAULT now(), fees jsonb DEFAULT '{}'::jsonb);
CREATE TABLE public.fee_item_groups (created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), fee_group_id integer NOT NULL, description text, author text NOT NULL DEFAULT 'System'::text, display_order integer NOT NULL DEFAULT 0, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.fee_items (description text, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), additional_info text, fee_group_id integer NOT NULL, value_type text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, default_value text, name text NOT NULL, author text NOT NULL DEFAULT 'System'::text, fee_item_group_id integer, display_order integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.locations (zip_code text NOT NULL, address text NOT NULL, state text NOT NULL, latitude numeric, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), mid character varying, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, phone text, status text NOT NULL DEFAULT 'active'::text, type text NOT NULL DEFAULT 'store'::text, merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), name text NOT NULL, email text, operating_hours jsonb, longitude numeric);
CREATE TABLE public.login_attempts (username character varying, ip_address character varying NOT NULL, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), user_agent text, email character varying, failure_reason character varying, success boolean NOT NULL);
CREATE TABLE public.merchant_prospects (id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), notes text, first_name text NOT NULL, validation_token text, validated_at timestamp without time zone, current_step integer DEFAULT 0, email text NOT NULL, status text NOT NULL DEFAULT 'pending'::text, updated_at timestamp without time zone NOT NULL DEFAULT now(), form_data text, application_started_at timestamp without time zone, agent_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), last_name text NOT NULL);
CREATE TABLE public.merchants (processing_fee numeric NOT NULL DEFAULT 2.50, website text, legal_name text, phone text NOT NULL, agent_id integer, status text NOT NULL DEFAULT 'active'::text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, user_id character varying, ein text, business_type text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, email text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), dba_name text, created_at timestamp without time zone NOT NULL DEFAULT now(), business_name text NOT NULL, industry text);
CREATE TABLE public.pdf_form_fields (section text, field_type text NOT NULL, options ARRAY, validation text, position integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), field_name text NOT NULL, created_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, field_label text NOT NULL, default_value text, is_required boolean DEFAULT false);
CREATE TABLE public.pdf_form_submissions (applicant_email text, is_public boolean DEFAULT false, status text DEFAULT 'draft'::text, submission_token text NOT NULL, updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, data text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), submitted_by text, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.pdf_forms (status text DEFAULT 'active'::text, updated_at timestamp without time zone DEFAULT now(), uploaded_by text NOT NULL, created_at timestamp without time zone DEFAULT now(), file_name text NOT NULL, navigation_title text, id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), file_size integer NOT NULL, allowed_roles ARRAY DEFAULT '{admin}'::text[], show_in_navigation boolean DEFAULT false, description text, name text NOT NULL);
CREATE TABLE public.pricing_type_fee_items (pricing_type_id integer NOT NULL, is_required boolean NOT NULL DEFAULT true, fee_item_id integer NOT NULL, display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.pricing_types (name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), description text, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.prospect_owners (email text NOT NULL, email_sent boolean DEFAULT false, created_at timestamp without time zone DEFAULT now(), email_sent_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), ownership_percentage numeric NOT NULL, prospect_id integer NOT NULL, updated_at timestamp without time zone DEFAULT now(), signature_token text, name text NOT NULL);
CREATE TABLE public.prospect_signatures (prospect_id integer NOT NULL, signature text NOT NULL, submitted_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), owner_id integer NOT NULL, signature_token text NOT NULL, signature_type text NOT NULL);
CREATE TABLE public.schema_migrations (applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, migration_id character varying NOT NULL, environment character varying NOT NULL, name character varying NOT NULL, checksum character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass));
CREATE TABLE public.security_events (severity text NOT NULL, assigned_to character varying, resolved_by character varying, audit_log_id integer, detected_by text, detection_method text, resolved_at timestamp without time zone, affected_users jsonb, detected_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), event_type text NOT NULL, affected_resources jsonb, investigation_notes text, updated_at timestamp without time zone NOT NULL DEFAULT now(), resolution text, mitigation_actions jsonb, alert_status text DEFAULT 'new'::text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.sessions (expire timestamp without time zone NOT NULL, sess jsonb NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (reference_number text, processing_fee numeric DEFAULT 0, commission_rate numeric DEFAULT 0.025, processed_at timestamp with time zone, payment_method text, amount numeric NOT NULL, status text NOT NULL, transaction_type text NOT NULL, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), commission_amount numeric DEFAULT 0, location_id integer, net_amount numeric DEFAULT 0, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, merchant_id integer NOT NULL, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.two_factor_codes (used boolean DEFAULT false, expires_at timestamp without time zone NOT NULL, type character varying NOT NULL, user_id character varying NOT NULL, code character varying NOT NULL, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.user_dashboard_preferences (id integer NOT NULL, position integer NOT NULL DEFAULT 0, size text NOT NULL DEFAULT 'medium'::text, user_id text NOT NULL, is_visible boolean NOT NULL DEFAULT true, widget_id text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), configuration jsonb DEFAULT '{}'::jsonb);
CREATE TABLE public.users (updated_at timestamp without time zone DEFAULT now(), password_hash character varying NOT NULL, last_login_ip character varying, permissions jsonb DEFAULT '{}'::jsonb, last_name character varying, profile_image_url character varying, username character varying NOT NULL, two_factor_enabled boolean DEFAULT false, timezone character varying DEFAULT 'UTC'::character varying, email_verified boolean DEFAULT false, id character varying NOT NULL, last_login_at timestamp without time zone, email_verification_token character varying, two_factor_secret character varying, first_name character varying, password_reset_expires timestamp without time zone, password_reset_token character varying, email character varying NOT NULL, status text NOT NULL DEFAULT 'active'::text, role text NOT NULL DEFAULT 'merchant'::text, created_at timestamp without time zone DEFAULT now());