-- Database backup for test environment
-- Generated at: 2025-09-26T04:06:58.120Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.acquirer_application_templates (version text NOT NULL DEFAULT '1.0'::text, conditional_fields jsonb, pdf_mapping_configuration jsonb, is_active boolean NOT NULL DEFAULT true, template_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), acquirer_id integer NOT NULL, required_fields ARRAY NOT NULL DEFAULT ARRAY[]::text[], updated_at timestamp without time zone NOT NULL DEFAULT now(), field_configuration jsonb NOT NULL, id integer NOT NULL DEFAULT nextval('acquirer_application_templates_id_seq'::regclass));
CREATE TABLE public.acquirers (code text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('acquirers_id_seq'::regclass), description text, name text NOT NULL, display_name text NOT NULL);
CREATE TABLE public.addresses (geo_accuracy real, city text NOT NULL, street2 text, geocoded_at timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), location_id integer NOT NULL, latitude real, longitude real, postal_code text NOT NULL, state text NOT NULL, country text NOT NULL DEFAULT 'US'::text, timezone text, type text NOT NULL DEFAULT 'primary'::text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), street1 text NOT NULL);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), agent_id integer NOT NULL, assigned_by text);
CREATE TABLE public.agents (created_at timestamp without time zone DEFAULT now(), last_name text NOT NULL, commission_rate numeric DEFAULT 5.00, user_id character varying NOT NULL, first_name text NOT NULL, company_id integer, email text NOT NULL, phone text NOT NULL, status text NOT NULL DEFAULT 'active'::text, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), territory text);
CREATE TABLE public.api_keys (key_id text NOT NULL, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), expires_at timestamp without time zone, last_used_at timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), organization_name text, rate_limit integer DEFAULT 1000, key_secret text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL, is_active boolean DEFAULT true, contact_email text NOT NULL, permissions jsonb NOT NULL DEFAULT '[]'::jsonb);
CREATE TABLE public.api_request_logs (error_message text, created_at timestamp without time zone NOT NULL DEFAULT now(), method text NOT NULL, response_size integer, user_agent text, response_time integer, ip_address text, api_key_id integer, status_code integer NOT NULL, endpoint text NOT NULL, request_size integer, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass));
CREATE TABLE public.audit_logs (endpoint text, application_version text, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), tags jsonb, geolocation jsonb, session_id text, old_values jsonb, action text NOT NULL, resource_id text, metadata jsonb, status_code integer, user_email text, timestamp timestamp without time zone NOT NULL DEFAULT now(), category text, resource text NOT NULL, severity text DEFAULT 'info'::text, user_agent text, environment text DEFAULT 'production'::text, ip_address text NOT NULL, request_body jsonb, updated_at timestamp without time zone DEFAULT now(), response_time integer, retention_policy text, notes text, error_message text, compliance_flags jsonb, device_info jsonb, details jsonb, created_at timestamp without time zone NOT NULL DEFAULT now(), resource_type text, data_classification text, user_id character varying, method text, request_params jsonb, correlation_id character varying, risk_level text NOT NULL DEFAULT 'low'::text, outcome text, new_values jsonb, request_id character varying, encryption_key_id character varying);
CREATE TABLE public.business_ownership (owner_name text NOT NULL, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), owner_email text NOT NULL, ownership_percentage numeric NOT NULL, signed_at timestamp without time zone, requires_signature boolean NOT NULL DEFAULT false, signature_image_path text, signature_type text, digital_signature text, signature_token text, prospect_id integer, form_submission_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaign_assignments (assigned_by character varying, application_id integer, is_active boolean NOT NULL DEFAULT true, id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), prospect_id integer, assigned_at timestamp without time zone NOT NULL DEFAULT now(), campaign_id integer NOT NULL);
CREATE TABLE public.campaign_equipment (display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_required boolean NOT NULL DEFAULT false, campaign_id integer NOT NULL, equipment_item_id integer NOT NULL);
CREATE TABLE public.campaign_fee_values (value text NOT NULL, campaign_id integer NOT NULL, fee_group_fee_item_id integer, fee_item_id integer, value_type text NOT NULL DEFAULT 'percentage'::text, id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.campaigns (name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, equipment text, currency text NOT NULL DEFAULT 'USD'::text, is_default boolean NOT NULL DEFAULT false, created_at timestamp without time zone NOT NULL DEFAULT now(), acquirer text, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), acquirer_id integer NOT NULL, description text, pricing_type_id integer, created_by character varying);
CREATE TABLE public.companies (email text, phone text, tax_id character varying, description text, created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('companies_id_seq'::regclass), logo_url text, address jsonb, name text NOT NULL, business_type text, industry text, updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, website text, status text NOT NULL DEFAULT 'active'::text);
CREATE TABLE public.data_access_logs (id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), record_id text, lawful_basis text, field_accessed text, access_reason text, retention_period integer, data_volume integer, user_id character varying NOT NULL, access_type text NOT NULL, audit_log_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), table_name text NOT NULL, data_type text NOT NULL);
CREATE TABLE public.email_activity (opened_at timestamp without time zone, recipient_email character varying NOT NULL, template_id integer, template_name character varying NOT NULL, metadata jsonb, recipient_name character varying, clicked_at timestamp without time zone, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), triggered_by character varying, trigger_source character varying, error_message text, sent_at timestamp without time zone DEFAULT now(), subject text NOT NULL, status character varying NOT NULL);
CREATE TABLE public.email_templates (description text, text_content text, category character varying NOT NULL, html_content text NOT NULL, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), is_active boolean DEFAULT true, updated_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), variables jsonb, subject text NOT NULL);
CREATE TABLE public.email_triggers (description text, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), trigger_event character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), name character varying NOT NULL, conditions jsonb, is_active boolean DEFAULT true, updated_at timestamp without time zone DEFAULT now(), template_id integer);
CREATE TABLE public.equipment_items (created_at timestamp without time zone NOT NULL DEFAULT now(), manufacturer text, updated_at timestamp without time zone NOT NULL DEFAULT now(), model text, is_active boolean NOT NULL DEFAULT true, category text, name text NOT NULL, status text DEFAULT 'available'::text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), description text, price numeric, specifications jsonb DEFAULT '{}'::jsonb, image_data text, model_number text, image_url text);
CREATE TABLE public.fee_group_fee_items (is_required boolean NOT NULL DEFAULT false, display_order integer NOT NULL DEFAULT 0, created_at timestamp without time zone DEFAULT now(), fee_item_id integer NOT NULL, fee_group_id integer NOT NULL, fee_item_group_id integer, id integer NOT NULL DEFAULT nextval('fee_group_fee_items_id_seq'::regclass));
CREATE TABLE public.fee_groups (category text, created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), fees jsonb DEFAULT '{}'::jsonb, author text NOT NULL DEFAULT 'System'::text, description text, created_by text, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL);
CREATE TABLE public.fee_item_groups (display_order integer NOT NULL DEFAULT 0, description text, fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass), is_active boolean NOT NULL DEFAULT true, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), name text NOT NULL);
CREATE TABLE public.fee_items (display_order integer NOT NULL DEFAULT 0, default_value text, created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_group_id integer, is_active boolean NOT NULL DEFAULT true, value_type text NOT NULL, name text NOT NULL, author text NOT NULL DEFAULT 'System'::text, additional_info text, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), description text, updated_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.locations (email text, zip_code text NOT NULL, status text NOT NULL DEFAULT 'active'::text, phone text, longitude numeric, name text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), state text NOT NULL, address text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, city text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), mid character varying, merchant_id integer NOT NULL, operating_hours jsonb, type text NOT NULL DEFAULT 'store'::text, latitude numeric);
CREATE TABLE public.login_attempts (failure_reason character varying, username character varying, email character varying, user_agent text, ip_address character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), success boolean NOT NULL);
CREATE TABLE public.merchant_prospects (form_data text, created_at timestamp without time zone NOT NULL DEFAULT now(), updated_at timestamp without time zone NOT NULL DEFAULT now(), last_name text NOT NULL, email text NOT NULL, agent_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), status text NOT NULL DEFAULT 'pending'::text, validated_at timestamp without time zone, current_step integer DEFAULT 0, application_started_at timestamp without time zone, validation_token text, notes text, first_name text NOT NULL);
CREATE TABLE public.merchants (monthly_volume numeric NOT NULL DEFAULT '0'::numeric, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, business_type text NOT NULL, industry text, legal_name text, phone text NOT NULL, ein text, user_id character varying, email text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), website text, company_id integer, dba_name text, processing_fee numeric NOT NULL DEFAULT 2.50, business_name text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'active'::text, agent_id integer);
CREATE TABLE public.pdf_form_fields (field_name text NOT NULL, section text, validation text, position integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), created_at timestamp without time zone DEFAULT now(), field_type text NOT NULL, field_label text NOT NULL, form_id integer NOT NULL, default_value text, options ARRAY, is_required boolean DEFAULT false);
CREATE TABLE public.pdf_form_submissions (submission_token text NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), status text DEFAULT 'draft'::text, created_at timestamp without time zone DEFAULT now(), submitted_by text, is_public boolean DEFAULT false, updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, data text NOT NULL, applicant_email text);
CREATE TABLE public.pdf_forms (uploaded_by text NOT NULL, file_name text NOT NULL, show_in_navigation boolean DEFAULT false, updated_at timestamp without time zone DEFAULT now(), status text DEFAULT 'active'::text, allowed_roles ARRAY DEFAULT '{admin}'::text[], created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), file_size integer NOT NULL, description text, name text NOT NULL, navigation_title text);
CREATE TABLE public.pricing_type_fee_items (created_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL, is_required boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, pricing_type_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass));
CREATE TABLE public.pricing_types (is_active boolean NOT NULL DEFAULT true, name text NOT NULL, description text, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), author text NOT NULL DEFAULT 'System'::text);
CREATE TABLE public.prospect_applications (generated_pdf_path text, rejection_reason text, created_at timestamp without time zone NOT NULL DEFAULT now(), acquirer_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_applications_id_seq'::regclass), submitted_at timestamp without time zone, rejected_at timestamp without time zone, prospect_id integer NOT NULL, template_id integer NOT NULL, approved_at timestamp without time zone, application_data jsonb NOT NULL DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'draft'::text, template_version text NOT NULL);
CREATE TABLE public.prospect_owners (updated_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), signature_token text, email_sent_at timestamp without time zone, email text NOT NULL, created_at timestamp without time zone DEFAULT now(), email_sent boolean DEFAULT false, prospect_id integer NOT NULL, ownership_percentage numeric NOT NULL, name text NOT NULL);
CREATE TABLE public.prospect_signatures (submitted_at timestamp without time zone DEFAULT now(), signature text NOT NULL, signature_type text NOT NULL, prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), owner_id integer NOT NULL, signature_token text NOT NULL);
CREATE TABLE public.schema_migrations (checksum character varying NOT NULL, id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), name character varying NOT NULL, migration_id character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, environment character varying NOT NULL);
CREATE TABLE public.security_events (assigned_to character varying, resolved_by character varying, resolved_at timestamp without time zone, affected_users jsonb, mitigation_actions jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), severity text NOT NULL, affected_resources jsonb, detected_by text, created_at timestamp without time zone NOT NULL DEFAULT now(), detection_method text, investigation_notes text, audit_log_id integer, detected_at timestamp without time zone NOT NULL DEFAULT now(), alert_status text DEFAULT 'new'::text, resolution text, event_type text NOT NULL, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass));
CREATE TABLE public.sessions (sid character varying NOT NULL, sess jsonb NOT NULL, expire timestamp without time zone NOT NULL);
CREATE TABLE public.transactions (reference_number text, created_at timestamp without time zone DEFAULT now(), transaction_type text NOT NULL, net_amount numeric DEFAULT 0, payment_method text, location_id integer, processing_fee numeric DEFAULT 0, commission_rate numeric DEFAULT 0.025, processed_at timestamp with time zone, transaction_id text NOT NULL DEFAULT ''::text, amount numeric NOT NULL, merchant_id integer NOT NULL, status text NOT NULL, commission_amount numeric DEFAULT 0, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), mid character varying);
CREATE TABLE public.two_factor_codes (user_id character varying NOT NULL, type character varying NOT NULL, code character varying NOT NULL, id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), expires_at timestamp without time zone NOT NULL, created_at timestamp without time zone DEFAULT now(), used boolean DEFAULT false);
CREATE TABLE public.user_company_associations (created_at timestamp without time zone NOT NULL DEFAULT now(), start_date timestamp without time zone, is_active boolean NOT NULL DEFAULT true, permissions jsonb DEFAULT '{}'::jsonb, end_date timestamp without time zone, company_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_primary boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('user_company_associations_id_seq'::regclass), department text, company_role text NOT NULL, user_id character varying NOT NULL, title text);
CREATE TABLE public.user_dashboard_preferences (configuration jsonb DEFAULT '{}'::jsonb, is_visible boolean NOT NULL DEFAULT true, widget_id text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), position integer NOT NULL DEFAULT 0, user_id text NOT NULL, id integer NOT NULL, size text NOT NULL DEFAULT 'medium'::text);
CREATE TABLE public.users (phone text NOT NULL DEFAULT ''::character varying, profile_image_url character varying, last_login_ip character varying, roles ARRAY DEFAULT '{merchant}'::text[], password_reset_token character varying, two_factor_secret character varying, email_verification_token character varying, last_login_at timestamp without time zone, status text NOT NULL DEFAULT 'active'::text, id character varying NOT NULL, password_reset_expires timestamp without time zone, first_name character varying, updated_at timestamp without time zone DEFAULT now(), email_verified boolean DEFAULT false, communication_preference text NOT NULL DEFAULT 'email'::text, last_name character varying, email character varying NOT NULL, two_factor_enabled boolean DEFAULT false, permissions jsonb DEFAULT '{}'::jsonb, username character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), timezone character varying DEFAULT 'UTC'::character varying, password_hash character varying NOT NULL);