-- Database backup for test environment
-- Generated at: 2025-08-18T18:05:17.278Z
-- Warning: This is a simplified backup for migration safety

CREATE TABLE public.addresses (created_at timestamp without time zone NOT NULL DEFAULT now(), geocoded_at timestamp without time zone, street2 text, id integer NOT NULL DEFAULT nextval('addresses_id_seq'::regclass), street1 text NOT NULL, longitude real, postal_code text NOT NULL, latitude real, geo_accuracy real, location_id integer NOT NULL, city text NOT NULL, type text NOT NULL DEFAULT 'primary'::text, timezone text, country text NOT NULL DEFAULT 'US'::text, state text NOT NULL);
CREATE TABLE public.agent_merchants (assigned_at timestamp without time zone DEFAULT now(), merchant_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('agent_merchants_id_seq'::regclass), agent_id integer NOT NULL, assigned_by text);
CREATE TABLE public.agents (commission_rate numeric DEFAULT 5.00, user_id character varying NOT NULL, first_name text NOT NULL, territory text, email text NOT NULL, id integer NOT NULL DEFAULT nextval('agents_id_seq'::regclass), status text NOT NULL DEFAULT 'active'::text, last_name text NOT NULL, phone text NOT NULL, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.api_keys (permissions jsonb NOT NULL DEFAULT '[]'::jsonb, expires_at timestamp without time zone, last_used_at timestamp without time zone, created_at timestamp without time zone NOT NULL DEFAULT now(), organization_name text, key_secret text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean DEFAULT true, rate_limit integer DEFAULT 1000, id integer NOT NULL DEFAULT nextval('api_keys_id_seq'::regclass), key_id text NOT NULL, contact_email text NOT NULL, name text NOT NULL);
CREATE TABLE public.api_request_logs (created_at timestamp without time zone NOT NULL DEFAULT now(), status_code integer NOT NULL, method text NOT NULL, error_message text, id integer NOT NULL DEFAULT nextval('api_request_logs_id_seq'::regclass), endpoint text NOT NULL, request_size integer, api_key_id integer, user_agent text, ip_address text, response_time integer, response_size integer);
CREATE TABLE public.audit_logs (user_email text, environment text DEFAULT 'production'::text, outcome text, resource_id text, new_values jsonb, request_id character varying, user_agent text, metadata jsonb, severity text DEFAULT 'info'::text, encryption_key_id character varying, resource text NOT NULL, user_id character varying, id integer NOT NULL DEFAULT nextval('audit_logs_id_seq'::regclass), data_classification text, resource_type text, created_at timestamp without time zone NOT NULL DEFAULT now(), application_version text, details jsonb, status_code integer, tags jsonb, geolocation jsonb, device_info jsonb, compliance_flags jsonb, method text, endpoint text, session_id text, request_params jsonb, error_message text, correlation_id character varying, notes text, retention_policy text, category text, old_values jsonb, response_time integer, updated_at timestamp without time zone DEFAULT now(), request_body jsonb, timestamp timestamp without time zone NOT NULL DEFAULT now(), action text NOT NULL, ip_address text NOT NULL, risk_level text NOT NULL DEFAULT 'low'::text);
CREATE TABLE public.business_ownership (created_at timestamp without time zone NOT NULL DEFAULT now(), requires_signature boolean NOT NULL DEFAULT false, digital_signature text, updated_at timestamp without time zone NOT NULL DEFAULT now(), prospect_id integer, id integer NOT NULL DEFAULT nextval('business_ownership_id_seq'::regclass), owner_name text NOT NULL, ownership_percentage numeric NOT NULL, signature_image_path text, owner_email text NOT NULL, form_submission_id integer, signature_type text, signature_token text, signed_at timestamp without time zone);
CREATE TABLE public.campaign_assignments (assigned_by character varying, campaign_id integer NOT NULL, assigned_at timestamp without time zone NOT NULL DEFAULT now(), id integer NOT NULL DEFAULT nextval('campaign_assignments_id_seq'::regclass), application_id integer, is_active boolean NOT NULL DEFAULT true, prospect_id integer);
CREATE TABLE public.campaign_equipment (created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, equipment_item_id integer NOT NULL, campaign_id integer NOT NULL, is_required boolean NOT NULL DEFAULT false, id integer NOT NULL DEFAULT nextval('campaign_equipment_id_seq'::regclass));
CREATE TABLE public.campaign_fee_values (id integer NOT NULL DEFAULT nextval('campaign_fee_values_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), value text NOT NULL, value_type text NOT NULL DEFAULT 'percentage'::text, campaign_id integer NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), fee_item_id integer NOT NULL);
CREATE TABLE public.campaigns (is_active boolean NOT NULL DEFAULT true, currency text NOT NULL DEFAULT 'USD'::text, pricing_type_id integer, description text, is_default boolean NOT NULL DEFAULT false, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_by character varying, acquirer text NOT NULL, id integer NOT NULL DEFAULT nextval('campaigns_id_seq'::regclass), equipment text, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.data_access_logs (data_volume integer, access_reason text, lawful_basis text, user_id character varying NOT NULL, field_accessed text, retention_period integer, id integer NOT NULL DEFAULT nextval('data_access_logs_id_seq'::regclass), record_id text, created_at timestamp without time zone NOT NULL DEFAULT now(), data_type text NOT NULL, table_name text NOT NULL, audit_log_id integer, access_type text NOT NULL);
CREATE TABLE public.email_activity (triggered_by character varying, id integer NOT NULL DEFAULT nextval('email_activity_id_seq'::regclass), template_name character varying NOT NULL, opened_at timestamp without time zone, recipient_email character varying NOT NULL, metadata jsonb, clicked_at timestamp without time zone, template_id integer, error_message text, trigger_source character varying, subject text NOT NULL, status character varying NOT NULL, recipient_name character varying, sent_at timestamp without time zone DEFAULT now());
CREATE TABLE public.email_templates (variables jsonb, name character varying NOT NULL, subject text NOT NULL, updated_at timestamp without time zone DEFAULT now(), description text, id integer NOT NULL DEFAULT nextval('email_templates_id_seq'::regclass), category character varying NOT NULL, is_active boolean DEFAULT true, text_content text, created_at timestamp without time zone DEFAULT now(), html_content text NOT NULL);
CREATE TABLE public.email_triggers (is_active boolean DEFAULT true, name character varying NOT NULL, id integer NOT NULL DEFAULT nextval('email_triggers_id_seq'::regclass), description text, created_at timestamp without time zone DEFAULT now(), trigger_event character varying NOT NULL, template_id integer, updated_at timestamp without time zone DEFAULT now(), conditions jsonb);
CREATE TABLE public.equipment_items (is_active boolean NOT NULL DEFAULT true, manufacturer text, specifications jsonb DEFAULT '{}'::jsonb, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), model_number text, category text, image_data text, created_at timestamp without time zone NOT NULL DEFAULT now(), model text, id integer NOT NULL DEFAULT nextval('equipment_items_id_seq'::regclass), status text DEFAULT 'available'::text, description text, image_url text, price numeric);
CREATE TABLE public.fee_groups (display_order integer NOT NULL DEFAULT 0, id integer NOT NULL DEFAULT nextval('fee_groups_id_seq'::regclass), fees jsonb DEFAULT '{}'::jsonb, updated_at timestamp without time zone NOT NULL DEFAULT now(), author text NOT NULL DEFAULT 'System'::text, created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, created_by text, category text, description text, name text NOT NULL);
CREATE TABLE public.fee_item_groups (is_active boolean NOT NULL DEFAULT true, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), created_at timestamp without time zone NOT NULL DEFAULT now(), display_order integer NOT NULL DEFAULT 0, fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, description text, id integer NOT NULL DEFAULT nextval('fee_item_groups_id_seq'::regclass));
CREATE TABLE public.fee_items (description text, created_at timestamp without time zone NOT NULL DEFAULT now(), fee_group_id integer NOT NULL, author text NOT NULL DEFAULT 'System'::text, fee_item_group_id integer, display_order integer NOT NULL DEFAULT 0, additional_info text, name text NOT NULL, value_type text NOT NULL, id integer NOT NULL DEFAULT nextval('fee_items_id_seq'::regclass), default_value text, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true);
CREATE TABLE public.locations (email text, phone text, status text NOT NULL DEFAULT 'active'::text, operating_hours jsonb, address text NOT NULL, name text NOT NULL, type text NOT NULL DEFAULT 'store'::text, merchant_id integer NOT NULL, zip_code text NOT NULL, id integer NOT NULL DEFAULT nextval('locations_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), city text NOT NULL, longitude numeric, mid character varying, state text NOT NULL, latitude numeric, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE public.login_attempts (email character varying, id integer NOT NULL DEFAULT nextval('login_attempts_id_seq'::regclass), ip_address character varying NOT NULL, user_agent text, success boolean NOT NULL, created_at timestamp without time zone DEFAULT now(), username character varying, failure_reason character varying);
CREATE TABLE public.merchant_prospects (status text NOT NULL DEFAULT 'pending'::text, notes text, form_data text, first_name text NOT NULL, current_step integer DEFAULT 0, id integer NOT NULL DEFAULT nextval('merchant_prospects_id_seq'::regclass), email text NOT NULL, application_started_at timestamp without time zone, validation_token text, last_name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), validated_at timestamp without time zone, agent_id integer NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.merchants (dba_name text, monthly_volume numeric NOT NULL DEFAULT '0'::numeric, agent_id integer, legal_name text, website text, business_name text NOT NULL, updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP, phone text NOT NULL, business_type text NOT NULL, id integer NOT NULL DEFAULT nextval('merchants_id_seq'::regclass), industry text, created_at timestamp without time zone NOT NULL DEFAULT now(), email text NOT NULL, processing_fee numeric NOT NULL DEFAULT 2.50, ein text, user_id character varying, status text NOT NULL DEFAULT 'active'::text);
CREATE TABLE public.pdf_form_fields (validation text, field_type text NOT NULL, form_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pdf_form_fields_id_seq'::regclass), section text, created_at timestamp without time zone DEFAULT now(), position integer NOT NULL, options ARRAY, is_required boolean DEFAULT false, default_value text, field_label text NOT NULL, field_name text NOT NULL);
CREATE TABLE public.pdf_form_submissions (status text DEFAULT 'draft'::text, applicant_email text, is_public boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('pdf_form_submissions_id_seq'::regclass), submitted_by text, data text NOT NULL, submission_token text NOT NULL, updated_at timestamp without time zone DEFAULT now(), form_id integer NOT NULL, created_at timestamp without time zone DEFAULT now());
CREATE TABLE public.pdf_forms (allowed_roles ARRAY DEFAULT '{admin}'::text[], file_name text NOT NULL, name text NOT NULL, updated_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('pdf_forms_id_seq'::regclass), status text DEFAULT 'active'::text, show_in_navigation boolean DEFAULT false, description text, uploaded_by text NOT NULL, created_at timestamp without time zone DEFAULT now(), file_size integer NOT NULL, navigation_title text);
CREATE TABLE public.pricing_type_fee_items (fee_item_id integer NOT NULL, is_required boolean NOT NULL DEFAULT true, display_order integer NOT NULL DEFAULT 0, pricing_type_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('pricing_type_fee_items_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now());
CREATE TABLE public.pricing_types (author text NOT NULL DEFAULT 'System'::text, id integer NOT NULL DEFAULT nextval('pricing_types_id_seq'::regclass), created_at timestamp without time zone NOT NULL DEFAULT now(), is_active boolean NOT NULL DEFAULT true, name text NOT NULL, updated_at timestamp without time zone NOT NULL DEFAULT now(), description text);
CREATE TABLE public.prospect_owners (prospect_id integer NOT NULL, created_at timestamp without time zone DEFAULT now(), email_sent_at timestamp without time zone, email text NOT NULL, email_sent boolean DEFAULT false, id integer NOT NULL DEFAULT nextval('prospect_owners_id_seq'::regclass), name text NOT NULL, ownership_percentage numeric NOT NULL, updated_at timestamp without time zone DEFAULT now(), signature_token text);
CREATE TABLE public.prospect_signatures (signature text NOT NULL, signature_type text NOT NULL, prospect_id integer NOT NULL, id integer NOT NULL DEFAULT nextval('prospect_signatures_id_seq'::regclass), submitted_at timestamp without time zone DEFAULT now(), owner_id integer NOT NULL, signature_token text NOT NULL);
CREATE TABLE public.schema_migrations (id integer NOT NULL DEFAULT nextval('schema_migrations_id_seq'::regclass), name character varying NOT NULL, environment character varying NOT NULL, migration_id character varying NOT NULL, applied_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, checksum character varying NOT NULL);
CREATE TABLE public.security_events (event_type text NOT NULL, alert_status text DEFAULT 'new'::text, investigation_notes text, detected_at timestamp without time zone NOT NULL DEFAULT now(), resolved_at timestamp without time zone, detection_method text, updated_at timestamp without time zone NOT NULL DEFAULT now(), affected_users jsonb, severity text NOT NULL, resolved_by character varying, id integer NOT NULL DEFAULT nextval('security_events_id_seq'::regclass), assigned_to character varying, audit_log_id integer, created_at timestamp without time zone NOT NULL DEFAULT now(), detected_by text, resolution text, affected_resources jsonb, mitigation_actions jsonb);
CREATE TABLE public.sessions (sess jsonb NOT NULL, expire timestamp without time zone NOT NULL, sid character varying NOT NULL);
CREATE TABLE public.transactions (created_at timestamp without time zone DEFAULT now(), reference_number text, location_id integer, processing_fee numeric DEFAULT 0, processed_at timestamp with time zone, transaction_id text NOT NULL DEFAULT ''::text, amount numeric NOT NULL, id integer NOT NULL DEFAULT nextval('transactions_id_seq'::regclass), commission_rate numeric DEFAULT 0.025, commission_amount numeric DEFAULT 0, mid character varying, merchant_id integer NOT NULL, status text NOT NULL, transaction_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP, payment_method text, net_amount numeric DEFAULT 0, transaction_type text NOT NULL);
CREATE TABLE public.two_factor_codes (expires_at timestamp without time zone NOT NULL, used boolean DEFAULT false, type character varying NOT NULL, code character varying NOT NULL, created_at timestamp without time zone DEFAULT now(), id integer NOT NULL DEFAULT nextval('two_factor_codes_id_seq'::regclass), user_id character varying NOT NULL);
CREATE TABLE public.user_dashboard_preferences (position integer NOT NULL DEFAULT 0, updated_at timestamp without time zone NOT NULL DEFAULT now(), is_visible boolean NOT NULL DEFAULT true, configuration jsonb DEFAULT '{}'::jsonb, user_id text NOT NULL, id integer NOT NULL, widget_id text NOT NULL, created_at timestamp without time zone NOT NULL DEFAULT now(), size text NOT NULL DEFAULT 'medium'::text);
CREATE TABLE public.users (email_verified boolean DEFAULT false, role text NOT NULL DEFAULT 'merchant'::text, password_reset_expires timestamp without time zone, last_name character varying, two_factor_enabled boolean DEFAULT false, username character varying NOT NULL, password_reset_token character varying, last_login_at timestamp without time zone, profile_image_url character varying, permissions jsonb DEFAULT '{}'::jsonb, email_verification_token character varying, email character varying NOT NULL, password_hash character varying NOT NULL, two_factor_secret character varying, last_login_ip character varying, created_at timestamp without time zone DEFAULT now(), first_name character varying, updated_at timestamp without time zone DEFAULT now(), id character varying NOT NULL, status text NOT NULL DEFAULT 'active'::text, timezone character varying DEFAULT 'UTC'::character varying);